// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata used for long running operations returned by CTS batch APIs.
/// It's used to replace
/// [google.longrunning.Operation.metadata][google.longrunning.Operation.metadata].
///
/// [google.longrunning.Operation.metadata]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/metadata
public struct BatchOperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The state of a long running operation.
  public var state: BatchOperationMetadata.State = BatchOperationMetadata.State()

  /// More detailed information about operation state.
  public var stateDescription: Swift.String = Swift.String()

  /// Count of successful item(s) inside an operation.
  public var successCount: Swift.Int32 = Swift.Int32()

  /// Count of failed item(s) inside an operation.
  public var failureCount: Swift.Int32 = Swift.Int32()

  /// Count of total item(s) inside an operation.
  public var totalCount: Swift.Int32 = Swift.Int32()

  /// The time when the batch operation is created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The time when the batch operation status is updated. The metadata and the
  /// [update_time][google.cloud.talent.v4.BatchOperationMetadata.update_time] is
  /// refreshed every minute otherwise cached data is returned.
  ///
  /// [google.cloud.talent.v4.BatchOperationMetadata.update_time]: <doc:BatchOperationMetadata/updateTime>
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// The time when the batch operation is finished and
  /// [google.longrunning.Operation.done][google.longrunning.Operation.done] is
  /// set to `true`.
  ///
  /// [google.longrunning.Operation.done]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/done
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `BatchOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchOperationMetadata().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum State: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// The batch operation is being prepared for processing.
    case initializing
    /// The batch operation is actively being processed.
    case processing
    /// The batch operation is processed, and at least one item has been
    /// successfully processed.
    case succeeded
    /// The batch operation is done and no item has been successfully processed.
    case failed
    /// The batch operation is in the process of cancelling after
    /// [google.longrunning.Operations.CancelOperation][google.longrunning.Operations.CancelOperation]
    /// is called.
    case cancelling
    /// The batch operation is done after
    /// [google.longrunning.Operations.CancelOperation][google.longrunning.Operations.CancelOperation]
    /// is called. Any items processed before cancelling are returned in the
    /// response.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .initializing: return 1
      case .processing: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .cancelling: return 5
      case .cancelled: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .initializing: return "INITIALIZING"
      case .processing: return "PROCESSING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .cancelling: return "CANCELLING"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "INITIALIZING": self = .initializing
      case "PROCESSING": self = .processing
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "CANCELLING": self = .cancelling
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .initializing
      case 2: self = .processing
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .cancelling
      case 6: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .initializing: return try container.encode(1)
      case .processing: return try container.encode(2)
      case .succeeded: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .cancelling: return try container.encode(5)
      case .cancelled: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.BatchOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
