// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An event issued when an end user interacts with the application that
/// implements Cloud Talent Solution. Providing this information improves the
/// quality of results for the API clients, enabling the
/// service to perform optimally. The number of events sent must be consistent
/// with other calls, such as job searches, issued to the service by the client.
public struct ClientEvent: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Strongly recommended for the best service experience.
  ///
  /// A unique ID generated in the API responses. It can be found in
  /// [ResponseMetadata.request_id][google.cloud.talent.v4.ResponseMetadata.request_id].
  ///
  /// [google.cloud.talent.v4.ResponseMetadata.request_id]: <doc:ResponseMetadata/requestId>
  public var requestId: Swift.String = Swift.String()

  /// Required. A unique identifier, generated by the client application.
  public var eventId: Swift.String = Swift.String()

  /// Required. The timestamp of the event.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Notes about the event provided by recruiters or other users, for example,
  /// feedback on why a job was bookmarked.
  public var eventNotes: Swift.String = Swift.String()

  /// Required.
  ///
  /// The detail information of a specific event type.
  public var event: OneOf_Event? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClientEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientEvent().with { $0.requestId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let requestId = CodingKeys(stringValue: "requestId")
    static let eventId = CodingKeys(stringValue: "eventId")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let jobEvent = CodingKeys(stringValue: "jobEvent")
    static let eventNotes = CodingKeys(stringValue: "eventNotes")

    static let _knownKeys: Set<Swift.String> = [
      "requestId",
      "eventId",
      "createTime",
      "jobEvent",
      "eventNotes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventId) {
      self.eventId = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventNotes) {
      self.eventNotes = value
    }

    var event: OneOf_Event? = nil
    let eventCheckAndSet = {
      if event != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'event'"))
      }
      event = $0
    }
    if let jobEvent = try container.decodeIfPresent(JobEvent?.self, forKey: .jobEvent) {
      try eventCheckAndSet(.jobEvent(jobEvent))
    }
    self.event = event
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.eventId, forKey: .eventId)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.eventNotes, forKey: .eventNotes)

    if let choice = self.event {
      switch choice {
      case .jobEvent(let value):
        try container.encode(value, forKey: .jobEvent)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required.
  ///
  /// The detail information of a specific event type.
  public enum OneOf_Event: Codable, Equatable, Sendable {
    /// An event issued when a job seeker interacts with the application that
    /// implements Cloud Talent Solution.
    indirect case jobEvent(JobEvent?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.ClientEvent"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
