// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Method for commute. Walking, biking and wheelchair accessible transit is
/// still in the Preview stage.
public enum CommuteMethod: Codable, Equatable, Sendable {
  /// Commute method isn't specified.
  case unspecified
  /// Commute time is calculated based on driving time.
  case driving
  /// Commute time is calculated based on public transit including bus, metro,
  /// subway, and so on.
  case transit
  /// Commute time is calculated based on walking time.
  case walking
  /// Commute time is calculated based on biking time.
  case cycling
  /// Commute time is calculated based on public transit that is wheelchair
  /// accessible.
  case transitAccessible
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .driving: return 1
    case .transit: return 2
    case .walking: return 3
    case .cycling: return 4
    case .transitAccessible: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "COMMUTE_METHOD_UNSPECIFIED"
    case .driving: return "DRIVING"
    case .transit: return "TRANSIT"
    case .walking: return "WALKING"
    case .cycling: return "CYCLING"
    case .transitAccessible: return "TRANSIT_ACCESSIBLE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CommuteMethod/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "COMMUTE_METHOD_UNSPECIFIED": self = .unspecified
    case "DRIVING": self = .driving
    case "TRANSIT": self = .transit
    case "WALKING": self = .walking
    case "CYCLING": self = .cycling
    case "TRANSIT_ACCESSIBLE": self = .transitAccessible
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CommuteMethod/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .driving
    case 2: self = .transit
    case 3: self = .walking
    case 4: self = .cycling
    case 5: self = .transitAccessible
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .driving: return try container.encode(1)
    case .transit: return try container.encode(2)
    case .walking: return try container.encode(3)
    case .cycling: return try container.encode(4)
    case .transitAccessible: return try container.encode(5)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
