// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Parameters needed for commute search.
public struct CommuteFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The method of transportation to calculate the commute time for.
  public var commuteMethod: CommuteMethod = CommuteMethod()

  /// Required. The latitude and longitude of the location to calculate the
  /// commute time from.
  public var startCoordinates: GoogleType.LatLng? = nil

  /// Required. The maximum travel time in seconds. The maximum allowed value is
  /// `3600s` (one hour). Format is `123s`.
  public var travelDuration: GoogleCloudWkt.Duration? = nil

  /// If `true`, jobs without street level addresses may also be returned.
  /// For city level addresses, the city center is used. For state and coarser
  /// level addresses, text matching is used.
  /// If this field is set to `false` or isn't specified, only jobs that include
  /// street level addresses will be returned by commute search.
  public var allowImpreciseAddresses: Swift.Bool = Swift.Bool()

  /// Traffic factor to take into account while searching by commute.
  public var trafficOption: OneOf_TrafficOption? = nil

  /// Initialize a new instance of `CommuteFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CommuteFilter().with { $0.commuteMethod = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case commuteMethod = "commuteMethod"
    case startCoordinates = "startCoordinates"
    case travelDuration = "travelDuration"
    case allowImpreciseAddresses = "allowImpreciseAddresses"
    case roadTraffic = "roadTraffic"
    case departureTime = "departureTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.commuteMethod = try container.decode(CommuteMethod.self, forKey: .commuteMethod)
    self.startCoordinates = try container.decodeIfPresent(
      GoogleType.LatLng.self, forKey: .startCoordinates)
    self.travelDuration = try container.decodeIfPresent(
      GoogleCloudWkt.Duration.self, forKey: .travelDuration)
    self.allowImpreciseAddresses = try container.decode(
      Swift.Bool.self, forKey: .allowImpreciseAddresses)

    var trafficOption: OneOf_TrafficOption? = nil
    let trafficOptionCheckAndSet = {
      if trafficOption != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'trafficOption'"))
      }
      trafficOption = $0
    }
    if let roadTraffic = try container.decodeIfPresent(
      CommuteFilter.RoadTraffic.self, forKey: .roadTraffic)
    {
      try trafficOptionCheckAndSet(.roadTraffic(roadTraffic))
    }
    if let departureTime = try container.decodeIfPresent(
      GoogleType.TimeOfDay?.self, forKey: .departureTime)
    {
      try trafficOptionCheckAndSet(.departureTime(departureTime))
    }
    self.trafficOption = trafficOption
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.commuteMethod, forKey: .commuteMethod)
    try container.encode(self.startCoordinates, forKey: .startCoordinates)
    try container.encode(self.travelDuration, forKey: .travelDuration)
    try container.encode(self.allowImpreciseAddresses, forKey: .allowImpreciseAddresses)

    if let choice = self.trafficOption {
      switch choice {
      case .roadTraffic(let value):
        try container.encode(value, forKey: .roadTraffic)
      case .departureTime(let value):
        try container.encode(value, forKey: .departureTime)
      }
    }
  }

  /// The traffic density to use when calculating commute time.
  public enum RoadTraffic: Codable, Equatable, Sendable {
    /// Road traffic situation isn't specified.
    case unspecified
    /// Optimal commute time without considering any traffic impact.
    case trafficFree
    /// Commute time calculation takes in account the peak traffic impact.
    case busyHour
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .trafficFree: return 1
      case .busyHour: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROAD_TRAFFIC_UNSPECIFIED"
      case .trafficFree: return "TRAFFIC_FREE"
      case .busyHour: return "BUSY_HOUR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROAD_TRAFFIC_UNSPECIFIED": self = .unspecified
      case "TRAFFIC_FREE": self = .trafficFree
      case "BUSY_HOUR": self = .busyHour
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .trafficFree
      case 2: self = .busyHour
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .trafficFree: return try container.encode(1)
      case .busyHour: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Traffic factor to take into account while searching by commute.
  public enum OneOf_TrafficOption: Codable, Equatable, Sendable {
    /// Specifies the traffic density to use when calculating commute time.
    case roadTraffic(CommuteFilter.RoadTraffic)
    /// The departure time used to calculate traffic impact, represented as
    /// [google.type.TimeOfDay][google.type.TimeOfDay] in local time zone.
    ///
    /// Currently traffic model is restricted to hour level resolution.
    ///
    /// [google.type.TimeOfDay]: https://www.google.com/search?q=Swift+google.type+GoogleType.TimeOfDay
    indirect case departureTime(GoogleType.TimeOfDay?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.CommuteFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
