// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Filter on job compensation type and amount.
public struct CompensationFilter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Type of filter.
  public var type: CompensationFilter.FilterType = CompensationFilter.FilterType()

  /// Required. Specify desired `base compensation entry's`
  /// [CompensationInfo.CompensationUnit][google.cloud.talent.v4.CompensationInfo.CompensationUnit].
  ///
  /// [google.cloud.talent.v4.CompensationInfo.CompensationUnit]: <doc:CompensationInfo/CompensationUnit>
  public var units: [CompensationInfo.CompensationUnit] = []

  /// Compensation range.
  public var range: CompensationInfo.CompensationRange? = nil

  /// If set to true, jobs with unspecified compensation range fields are
  /// included.
  public var includeJobsWithUnspecifiedCompensationRange: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CompensationFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CompensationFilter().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let units = CodingKeys(stringValue: "units")
    static let range = CodingKeys(stringValue: "range")
    static let includeJobsWithUnspecifiedCompensationRange = CodingKeys(
      stringValue: "includeJobsWithUnspecifiedCompensationRange")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "units",
      "range",
      "includeJobsWithUnspecifiedCompensationRange",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(CompensationFilter.FilterType.self, forKey: .type)
    {
      self.type = value
    }
    if let value = try container.decodeIfPresent(
      [CompensationInfo.CompensationUnit].self, forKey: .units)
    {
      self.units = value
    }
    self.range = try container.decodeIfPresent(
      CompensationInfo.CompensationRange.self, forKey: .range)
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .includeJobsWithUnspecifiedCompensationRange)
    {
      self.includeJobsWithUnspecifiedCompensationRange = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.units, forKey: .units)
    try container.encodeIfPresent(self.range, forKey: .range)
    try container.encode(
      self.includeJobsWithUnspecifiedCompensationRange,
      forKey: .includeJobsWithUnspecifiedCompensationRange)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specify the type of filtering.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum FilterType: Codable, Equatable, Sendable {
    /// Filter type unspecified. Position holder, INVALID, should never be used.
    case unspecified
    /// Filter by `base compensation entry's` unit. A job is a match if and
    /// only if the job contains a base CompensationEntry and the base
    /// CompensationEntry's unit matches provided
    /// [units][google.cloud.talent.v4.CompensationFilter.units]. Populate one or
    /// more [units][google.cloud.talent.v4.CompensationFilter.units].
    ///
    /// See
    /// [CompensationInfo.CompensationEntry][google.cloud.talent.v4.CompensationInfo.CompensationEntry]
    /// for definition of base compensation entry.
    ///
    /// [google.cloud.talent.v4.CompensationFilter.units]: <doc:CompensationFilter/units>
    /// [google.cloud.talent.v4.CompensationInfo.CompensationEntry]: <doc:CompensationInfo/CompensationEntry>
    case unitOnly
    /// Filter by `base compensation entry's` unit and amount / range. A job
    /// is a match if and only if the job contains a base CompensationEntry, and
    /// the base entry's unit matches provided
    /// [CompensationUnit][google.cloud.talent.v4.CompensationInfo.CompensationUnit]
    /// and amount or range overlaps with provided
    /// [CompensationRange][google.cloud.talent.v4.CompensationInfo.CompensationRange].
    ///
    /// See
    /// [CompensationInfo.CompensationEntry][google.cloud.talent.v4.CompensationInfo.CompensationEntry]
    /// for definition of base compensation entry.
    ///
    /// Set exactly one [units][google.cloud.talent.v4.CompensationFilter.units]
    /// and populate [range][google.cloud.talent.v4.CompensationFilter.range].
    ///
    /// [google.cloud.talent.v4.CompensationFilter.range]: <doc:CompensationFilter/range>
    /// [google.cloud.talent.v4.CompensationFilter.units]: <doc:CompensationFilter/units>
    /// [google.cloud.talent.v4.CompensationInfo.CompensationEntry]: <doc:CompensationInfo/CompensationEntry>
    /// [google.cloud.talent.v4.CompensationInfo.CompensationRange]: <doc:CompensationInfo/CompensationRange>
    /// [google.cloud.talent.v4.CompensationInfo.CompensationUnit]: <doc:CompensationInfo/CompensationUnit>
    case unitAndAmount
    /// Filter by annualized base compensation amount and `base compensation
    /// entry's` unit. Populate
    /// [range][google.cloud.talent.v4.CompensationFilter.range] and zero or more
    /// [units][google.cloud.talent.v4.CompensationFilter.units].
    ///
    /// [google.cloud.talent.v4.CompensationFilter.range]: <doc:CompensationFilter/range>
    /// [google.cloud.talent.v4.CompensationFilter.units]: <doc:CompensationFilter/units>
    case annualizedBaseAmount
    /// Filter by annualized total compensation amount and `base compensation
    /// entry's` unit . Populate
    /// [range][google.cloud.talent.v4.CompensationFilter.range] and zero or more
    /// [units][google.cloud.talent.v4.CompensationFilter.units].
    ///
    /// [google.cloud.talent.v4.CompensationFilter.range]: <doc:CompensationFilter/range>
    /// [google.cloud.talent.v4.CompensationFilter.units]: <doc:CompensationFilter/units>
    case annualizedTotalAmount
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unitOnly: return 1
      case .unitAndAmount: return 2
      case .annualizedBaseAmount: return 3
      case .annualizedTotalAmount: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FILTER_TYPE_UNSPECIFIED"
      case .unitOnly: return "UNIT_ONLY"
      case .unitAndAmount: return "UNIT_AND_AMOUNT"
      case .annualizedBaseAmount: return "ANNUALIZED_BASE_AMOUNT"
      case .annualizedTotalAmount: return "ANNUALIZED_TOTAL_AMOUNT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FilterType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FILTER_TYPE_UNSPECIFIED": self = .unspecified
      case "UNIT_ONLY": self = .unitOnly
      case "UNIT_AND_AMOUNT": self = .unitAndAmount
      case "ANNUALIZED_BASE_AMOUNT": self = .annualizedBaseAmount
      case "ANNUALIZED_TOTAL_AMOUNT": self = .annualizedTotalAmount
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FilterType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unitOnly
      case 2: self = .unitAndAmount
      case 3: self = .annualizedBaseAmount
      case 4: self = .annualizedTotalAmount
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FILTER_TYPE_UNSPECIFIED")
      case .unitOnly: return try container.encode("UNIT_ONLY")
      case .unitAndAmount: return try container.encode("UNIT_AND_AMOUNT")
      case .annualizedBaseAmount: return try container.encode("ANNUALIZED_BASE_AMOUNT")
      case .annualizedTotalAmount: return try container.encode("ANNUALIZED_TOTAL_AMOUNT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.CompensationFilter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
