// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A Company resource represents a company in the service. A company is the
/// entity that owns job postings, that is, the hiring entity responsible for
/// employing applicants for the job position.
public struct Company: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required during company update.
  ///
  /// The resource name for a company. This is generated by the service when a
  /// company is created.
  ///
  /// The format is
  /// "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}", for
  /// example, "projects/foo/tenants/bar/companies/baz".
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the company, for example, "Google LLC".
  public var displayName: Swift.String = Swift.String()

  /// Required. Client side company identifier, used to uniquely identify the
  /// company.
  ///
  /// The maximum number of allowed characters is 255.
  public var externalId: Swift.String = Swift.String()

  /// The employer's company size.
  public var size: CompanySize = CompanySize()

  /// The street address of the company's main headquarters, which may be
  /// different from the job location. The service attempts
  /// to geolocate the provided address, and populates a more specific
  /// location wherever possible in
  /// [DerivedInfo.headquarters_location][google.cloud.talent.v4.Company.DerivedInfo.headquarters_location].
  ///
  /// [google.cloud.talent.v4.Company.DerivedInfo.headquarters_location]: <doc:Company/DerivedInfo/headquartersLocation>
  public var headquartersAddress: Swift.String = Swift.String()

  /// Set to true if it is the hiring agency that post jobs for other
  /// employers.
  ///
  /// Defaults to false if not provided.
  public var hiringAgency: Swift.Bool = Swift.Bool()

  /// Equal Employment Opportunity legal disclaimer text to be
  /// associated with all jobs, and typically to be displayed in all
  /// roles.
  ///
  /// The maximum number of allowed characters is 500.
  public var eeoText: Swift.String = Swift.String()

  /// The URI representing the company's primary web site or home page,
  /// for example, "https://www.google.com".
  ///
  /// The maximum number of allowed characters is 255.
  public var websiteUri: Swift.String = Swift.String()

  /// The URI to employer's career site or careers page on the employer's web
  /// site, for example, "https://careers.google.com".
  public var careerSiteUri: Swift.String = Swift.String()

  /// A URI that hosts the employer's company logo.
  public var imageUri: Swift.String = Swift.String()

  /// This field is deprecated. Please set the searchability of the custom
  /// attribute in the
  /// [Job.custom_attributes][google.cloud.talent.v4.Job.custom_attributes] going
  /// forward.
  ///
  /// A list of keys of filterable
  /// [Job.custom_attributes][google.cloud.talent.v4.Job.custom_attributes],
  /// whose corresponding `string_values` are used in keyword searches. Jobs with
  /// `string_values` under these specified field keys are returned if any
  /// of the values match the search keyword. Custom field values with
  /// parenthesis, brackets and special symbols are not searchable as-is,
  /// and those keyword queries must be surrounded by quotes.
  ///
  /// [google.cloud.talent.v4.Job.custom_attributes]: <doc:Job/customAttributes>
  @available(*, deprecated)
  public var keywordSearchableJobCustomAttributes: [Swift.String] = []

  /// Output only. Derived details about the company.
  public var derivedInfo: Company.DerivedInfo? = nil

  /// Output only. Indicates whether a company is flagged to be suspended from
  /// public availability by the service when job content appears suspicious,
  /// abusive, or spammy.
  public var suspended: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Company`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Company().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let externalId = CodingKeys(stringValue: "externalId")
    static let size = CodingKeys(stringValue: "size")
    static let headquartersAddress = CodingKeys(stringValue: "headquartersAddress")
    static let hiringAgency = CodingKeys(stringValue: "hiringAgency")
    static let eeoText = CodingKeys(stringValue: "eeoText")
    static let websiteUri = CodingKeys(stringValue: "websiteUri")
    static let careerSiteUri = CodingKeys(stringValue: "careerSiteUri")
    static let imageUri = CodingKeys(stringValue: "imageUri")
    static let keywordSearchableJobCustomAttributes = CodingKeys(
      stringValue: "keywordSearchableJobCustomAttributes")
    static let derivedInfo = CodingKeys(stringValue: "derivedInfo")
    static let suspended = CodingKeys(stringValue: "suspended")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "externalId",
      "size",
      "headquartersAddress",
      "hiringAgency",
      "eeoText",
      "websiteUri",
      "careerSiteUri",
      "imageUri",
      "keywordSearchableJobCustomAttributes",
      "derivedInfo",
      "suspended",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalId) {
      self.externalId = value
    }
    if let value = try container.decodeIfPresent(CompanySize.self, forKey: .size) {
      self.size = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .headquartersAddress) {
      self.headquartersAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hiringAgency) {
      self.hiringAgency = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eeoText) {
      self.eeoText = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .websiteUri) {
      self.websiteUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .careerSiteUri) {
      self.careerSiteUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageUri) {
      self.imageUri = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .keywordSearchableJobCustomAttributes)
    {
      self.keywordSearchableJobCustomAttributes = value
    }
    self.derivedInfo = try container.decodeIfPresent(Company.DerivedInfo.self, forKey: .derivedInfo)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .suspended) {
      self.suspended = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.externalId, forKey: .externalId)
    try container.encode(self.size, forKey: .size)
    try container.encode(self.headquartersAddress, forKey: .headquartersAddress)
    try container.encode(self.hiringAgency, forKey: .hiringAgency)
    try container.encode(self.eeoText, forKey: .eeoText)
    try container.encode(self.websiteUri, forKey: .websiteUri)
    try container.encode(self.careerSiteUri, forKey: .careerSiteUri)
    try container.encode(self.imageUri, forKey: .imageUri)
    try container.encode(
      self.keywordSearchableJobCustomAttributes, forKey: .keywordSearchableJobCustomAttributes)
    try container.encodeIfPresent(self.derivedInfo, forKey: .derivedInfo)
    try container.encode(self.suspended, forKey: .suspended)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Derived details about the company.
  public struct DerivedInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A structured headquarters location of the company, resolved from
    /// [Company.headquarters_address][google.cloud.talent.v4.Company.headquarters_address]
    /// if provided.
    ///
    /// [google.cloud.talent.v4.Company.headquarters_address]: <doc:Company/headquartersAddress>
    public var headquartersLocation: Location? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DerivedInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DerivedInfo().with { $0.headquartersLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let headquartersLocation = CodingKeys(stringValue: "headquartersLocation")

      static let _knownKeys: Set<Swift.String> = [
        "headquartersLocation"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.headquartersLocation = try container.decodeIfPresent(
        Location.self, forKey: .headquartersLocation)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.headquartersLocation, forKey: .headquartersLocation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.talent.v4.Company.DerivedInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.Company"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
