// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class CompanyServiceLogging: CompanyServiceStub {
    let inner: any CompanyServiceStub
    let logger: Logger

    public init(_ inner: any CompanyServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-talent-v4"
      logger[metadataKey: "gcp.client.service"] = "jobs"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CompanyService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createCompany(
      request: CreateCompanyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Company {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCompany",
        action: {
          (r: CreateCompanyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Company
          in
          return try await self.inner.createCompany(request: r, options: o)
        })
    }

    public func getCompany(
      request: GetCompanyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Company {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCompany",
        action: {
          (r: GetCompanyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Company
          in
          return try await self.inner.getCompany(request: r, options: o)
        })
    }

    public func updateCompany(
      request: UpdateCompanyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Company {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCompany",
        action: {
          (r: UpdateCompanyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Company
          in
          return try await self.inner.updateCompany(request: r, options: o)
        })
    }

    public func deleteCompany(
      request: DeleteCompanyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCompany",
        action: {
          (r: DeleteCompanyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteCompany(request: r, options: o)
        })
    }

    public func listCompanies(
      request: ListCompaniesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListCompaniesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCompanies",
        action: {
          (r: ListCompaniesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.ListCompaniesResponse
          in
          return try await self.inner.listCompanies(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
