// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A Company resource represents a company in the service. A company is the
/// entity that owns job postings, that is, the hiring entity responsible for
/// employing applicants for the job position.
public struct Company: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required during company update.
  ///
  /// The resource name for a company. This is generated by the service when a
  /// company is created.
  ///
  /// The format is
  /// "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}", for
  /// example, "projects/foo/tenants/bar/companies/baz".
  public var name: Swift.String = Swift.String()

  /// Required. The display name of the company, for example, "Google LLC".
  public var displayName: Swift.String = Swift.String()

  /// Required. Client side company identifier, used to uniquely identify the
  /// company.
  ///
  /// The maximum number of allowed characters is 255.
  public var externalId: Swift.String = Swift.String()

  /// The employer's company size.
  public var size: CompanySize = CompanySize()

  /// The street address of the company's main headquarters, which may be
  /// different from the job location. The service attempts
  /// to geolocate the provided address, and populates a more specific
  /// location wherever possible in
  /// [DerivedInfo.headquarters_location][google.cloud.talent.v4.Company.DerivedInfo.headquarters_location].
  ///
  /// [google.cloud.talent.v4.Company.DerivedInfo.headquarters_location]: <doc:Company/DerivedInfo/headquartersLocation>
  public var headquartersAddress: Swift.String = Swift.String()

  /// Set to true if it is the hiring agency that post jobs for other
  /// employers.
  ///
  /// Defaults to false if not provided.
  public var hiringAgency: Swift.Bool = Swift.Bool()

  /// Equal Employment Opportunity legal disclaimer text to be
  /// associated with all jobs, and typically to be displayed in all
  /// roles.
  ///
  /// The maximum number of allowed characters is 500.
  public var eeoText: Swift.String = Swift.String()

  /// The URI representing the company's primary web site or home page,
  /// for example, "https://www.google.com".
  ///
  /// The maximum number of allowed characters is 255.
  public var websiteUri: Swift.String = Swift.String()

  /// The URI to employer's career site or careers page on the employer's web
  /// site, for example, "https://careers.google.com".
  public var careerSiteUri: Swift.String = Swift.String()

  /// A URI that hosts the employer's company logo.
  public var imageUri: Swift.String = Swift.String()

  /// This field is deprecated. Please set the searchability of the custom
  /// attribute in the
  /// [Job.custom_attributes][google.cloud.talent.v4.Job.custom_attributes] going
  /// forward.
  ///
  /// A list of keys of filterable
  /// [Job.custom_attributes][google.cloud.talent.v4.Job.custom_attributes],
  /// whose corresponding `string_values` are used in keyword searches. Jobs with
  /// `string_values` under these specified field keys are returned if any
  /// of the values match the search keyword. Custom field values with
  /// parenthesis, brackets and special symbols are not searchable as-is,
  /// and those keyword queries must be surrounded by quotes.
  ///
  /// [google.cloud.talent.v4.Job.custom_attributes]: <doc:Job/customAttributes>
  @available(*, deprecated)
  public var keywordSearchableJobCustomAttributes: [Swift.String] = []

  /// Output only. Derived details about the company.
  public var derivedInfo: Company.DerivedInfo? = nil

  /// Output only. Indicates whether a company is flagged to be suspended from
  /// public availability by the service when job content appears suspicious,
  /// abusive, or spammy.
  public var suspended: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Company`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Company().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Derived details about the company.
  public struct DerivedInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A structured headquarters location of the company, resolved from
    /// [Company.headquarters_address][google.cloud.talent.v4.Company.headquarters_address]
    /// if provided.
    ///
    /// [google.cloud.talent.v4.Company.headquarters_address]: <doc:Company/headquartersAddress>
    public var headquartersLocation: Location? = nil

    /// Initialize a new instance of `DerivedInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DerivedInfo().with { $0.headquartersLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.talent.v4.Company.DerivedInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.talent.v4.Company"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
