// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An enum that represents the size of the company.
public enum CompanySize: Codable, Equatable, Sendable {
  /// Default value if the size isn't specified.
  case unspecified
  /// The company has less than 50 employees.
  case mini
  /// The company has between 50 and 99 employees.
  case small
  /// The company has between 100 and 499 employees.
  case smedium
  /// The company has between 500 and 999 employees.
  case medium
  /// The company has between 1,000 and 4,999 employees.
  case big
  /// The company has between 5,000 and 9,999 employees.
  case bigger
  /// The company has 10,000 or more employees.
  case giant
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .mini: return 1
    case .small: return 2
    case .smedium: return 3
    case .medium: return 4
    case .big: return 5
    case .bigger: return 6
    case .giant: return 7
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "COMPANY_SIZE_UNSPECIFIED"
    case .mini: return "MINI"
    case .small: return "SMALL"
    case .smedium: return "SMEDIUM"
    case .medium: return "MEDIUM"
    case .big: return "BIG"
    case .bigger: return "BIGGER"
    case .giant: return "GIANT"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "COMPANY_SIZE_UNSPECIFIED": self = .unspecified
    case "MINI": self = .mini
    case "SMALL": self = .small
    case "SMEDIUM": self = .smedium
    case "MEDIUM": self = .medium
    case "BIG": self = .big
    case "BIGGER": self = .bigger
    case "GIANT": self = .giant
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .mini
    case 2: self = .small
    case 3: self = .smedium
    case 4: self = .medium
    case 5: self = .big
    case 6: self = .bigger
    case 7: self = .giant
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .mini: return try container.encode(1)
    case .small: return try container.encode(2)
    case .smedium: return try container.encode(3)
    case .medium: return try container.encode(4)
    case .big: return try container.encode(5)
    case .bigger: return try container.encode(6)
    case .giant: return try container.encode(7)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
