// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleCloudGax

/// A service handles auto completion.
///
/// @Snippet(path: "CompletionQuickstart")
public class CompletionClient: Clients.CompletionProtocol {
  let inner: any Clients.CompletionStub

  /// Creates a new `CompletionClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.CompletionStub = try Clients.CompletionTransport(options)
    inner = Clients.CompletionRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CompletionLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Completes the specified prefix with keyword suggestions.
  /// Intended for use by a job search auto-complete search box.
  ///
  /// @Snippet(path: "Completion_CompleteQuery")
  public func completeQuery(
    request: CompleteQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.CompleteQueryResponse {
    try await self.inner.completeQuery(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Completion_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CompletionClient`.
  ///
  /// To mock `CompletionClient` change your functions to receive
  /// `some CompletionProtocol` or `any CompletionProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CompletionProtocol {
    /// See `CompletionClient.completeQuery`.
    func completeQuery(request: CompleteQueryRequest) async throws
      -> GoogleCloudTalentV4.CompleteQueryResponse

    /// See `CompletionClient.completeQuery`.
    func completeQuery(
      request: CompleteQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.CompleteQueryResponse
  }
}

// Default implementations
extension Clients.CompletionProtocol {
  public func completeQuery(request: CompleteQueryRequest) async throws
    -> GoogleCloudTalentV4.CompleteQueryResponse
  {
    try await self.completeQuery(request: request, options: .init())
  }

  public func completeQuery(
    request: CompleteQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.CompleteQueryResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
