// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An enum that represents the categorization or primary focus of specific
/// role. This value is different than the "industry" associated with a role,
/// which is related to the categorization of the company listing the job.
public enum JobCategory: Codable, Equatable, Sendable {
  /// The default value if the category isn't specified.
  case unspecified
  /// An accounting and finance job, such as an Accountant.
  case accountingAndFinance
  /// An administrative and office job, such as an Administrative Assistant.
  case administrativeAndOffice
  /// An advertising and marketing job, such as Marketing Manager.
  case advertisingAndMarketing
  /// An animal care job, such as Veterinarian.
  case animalCare
  /// An art, fashion, or design job, such as Designer.
  case artFashionAndDesign
  /// A business operations job, such as Business Operations Manager.
  case businessOperations
  /// A cleaning and facilities job, such as Custodial Staff.
  case cleaningAndFacilities
  /// A computer and IT job, such as Systems Administrator.
  case computerAndIt
  /// A construction job, such as General Laborer.
  case construction
  /// A customer service job, such s Cashier.
  case customerService
  /// An education job, such as School Teacher.
  case education
  /// An entertainment and travel job, such as Flight Attendant.
  case entertainmentAndTravel
  /// A farming or outdoor job, such as Park Ranger.
  case farmingAndOutdoors
  /// A healthcare job, such as Registered Nurse.
  case healthcare
  /// A human resources job, such as Human Resources Director.
  case humanResources
  /// An installation, maintenance, or repair job, such as Electrician.
  case installationMaintenanceAndRepair
  /// A legal job, such as Law Clerk.
  case legal
  /// A management job, often used in conjunction with another category,
  /// such as Store Manager.
  case management
  /// A manufacturing or warehouse job, such as Assembly Technician.
  case manufacturingAndWarehouse
  /// A media, communications, or writing job, such as Media Relations.
  case mediaCommunicationsAndWriting
  /// An oil, gas or mining job, such as Offshore Driller.
  case oilGasAndMining
  /// A personal care and services job, such as Hair Stylist.
  case personalCareAndServices
  /// A protective services job, such as Security Guard.
  case protectiveServices
  /// A real estate job, such as Buyer's Agent.
  case realEstate
  /// A restaurant and hospitality job, such as Restaurant Server.
  case restaurantAndHospitality
  /// A sales and/or retail job, such Sales Associate.
  case salesAndRetail
  /// A science and engineering job, such as Lab Technician.
  case scienceAndEngineering
  /// A social services or non-profit job, such as Case Worker.
  case socialServicesAndNonProfit
  /// A sports, fitness, or recreation job, such as Personal Trainer.
  case sportsFitnessAndRecreation
  /// A transportation or logistics job, such as Truck Driver.
  case transportationAndLogistics
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .accountingAndFinance: return 1
    case .administrativeAndOffice: return 2
    case .advertisingAndMarketing: return 3
    case .animalCare: return 4
    case .artFashionAndDesign: return 5
    case .businessOperations: return 6
    case .cleaningAndFacilities: return 7
    case .computerAndIt: return 8
    case .construction: return 9
    case .customerService: return 10
    case .education: return 11
    case .entertainmentAndTravel: return 12
    case .farmingAndOutdoors: return 13
    case .healthcare: return 14
    case .humanResources: return 15
    case .installationMaintenanceAndRepair: return 16
    case .legal: return 17
    case .management: return 18
    case .manufacturingAndWarehouse: return 19
    case .mediaCommunicationsAndWriting: return 20
    case .oilGasAndMining: return 21
    case .personalCareAndServices: return 22
    case .protectiveServices: return 23
    case .realEstate: return 24
    case .restaurantAndHospitality: return 25
    case .salesAndRetail: return 26
    case .scienceAndEngineering: return 27
    case .socialServicesAndNonProfit: return 28
    case .sportsFitnessAndRecreation: return 29
    case .transportationAndLogistics: return 30
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .unspecified: return "JOB_CATEGORY_UNSPECIFIED"
    case .accountingAndFinance: return "ACCOUNTING_AND_FINANCE"
    case .administrativeAndOffice: return "ADMINISTRATIVE_AND_OFFICE"
    case .advertisingAndMarketing: return "ADVERTISING_AND_MARKETING"
    case .animalCare: return "ANIMAL_CARE"
    case .artFashionAndDesign: return "ART_FASHION_AND_DESIGN"
    case .businessOperations: return "BUSINESS_OPERATIONS"
    case .cleaningAndFacilities: return "CLEANING_AND_FACILITIES"
    case .computerAndIt: return "COMPUTER_AND_IT"
    case .construction: return "CONSTRUCTION"
    case .customerService: return "CUSTOMER_SERVICE"
    case .education: return "EDUCATION"
    case .entertainmentAndTravel: return "ENTERTAINMENT_AND_TRAVEL"
    case .farmingAndOutdoors: return "FARMING_AND_OUTDOORS"
    case .healthcare: return "HEALTHCARE"
    case .humanResources: return "HUMAN_RESOURCES"
    case .installationMaintenanceAndRepair: return "INSTALLATION_MAINTENANCE_AND_REPAIR"
    case .legal: return "LEGAL"
    case .management: return "MANAGEMENT"
    case .manufacturingAndWarehouse: return "MANUFACTURING_AND_WAREHOUSE"
    case .mediaCommunicationsAndWriting: return "MEDIA_COMMUNICATIONS_AND_WRITING"
    case .oilGasAndMining: return "OIL_GAS_AND_MINING"
    case .personalCareAndServices: return "PERSONAL_CARE_AND_SERVICES"
    case .protectiveServices: return "PROTECTIVE_SERVICES"
    case .realEstate: return "REAL_ESTATE"
    case .restaurantAndHospitality: return "RESTAURANT_AND_HOSPITALITY"
    case .salesAndRetail: return "SALES_AND_RETAIL"
    case .scienceAndEngineering: return "SCIENCE_AND_ENGINEERING"
    case .socialServicesAndNonProfit: return "SOCIAL_SERVICES_AND_NON_PROFIT"
    case .sportsFitnessAndRecreation: return "SPORTS_FITNESS_AND_RECREATION"
    case .transportationAndLogistics: return "TRANSPORTATION_AND_LOGISTICS"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "JOB_CATEGORY_UNSPECIFIED": self = .unspecified
    case "ACCOUNTING_AND_FINANCE": self = .accountingAndFinance
    case "ADMINISTRATIVE_AND_OFFICE": self = .administrativeAndOffice
    case "ADVERTISING_AND_MARKETING": self = .advertisingAndMarketing
    case "ANIMAL_CARE": self = .animalCare
    case "ART_FASHION_AND_DESIGN": self = .artFashionAndDesign
    case "BUSINESS_OPERATIONS": self = .businessOperations
    case "CLEANING_AND_FACILITIES": self = .cleaningAndFacilities
    case "COMPUTER_AND_IT": self = .computerAndIt
    case "CONSTRUCTION": self = .construction
    case "CUSTOMER_SERVICE": self = .customerService
    case "EDUCATION": self = .education
    case "ENTERTAINMENT_AND_TRAVEL": self = .entertainmentAndTravel
    case "FARMING_AND_OUTDOORS": self = .farmingAndOutdoors
    case "HEALTHCARE": self = .healthcare
    case "HUMAN_RESOURCES": self = .humanResources
    case "INSTALLATION_MAINTENANCE_AND_REPAIR": self = .installationMaintenanceAndRepair
    case "LEGAL": self = .legal
    case "MANAGEMENT": self = .management
    case "MANUFACTURING_AND_WAREHOUSE": self = .manufacturingAndWarehouse
    case "MEDIA_COMMUNICATIONS_AND_WRITING": self = .mediaCommunicationsAndWriting
    case "OIL_GAS_AND_MINING": self = .oilGasAndMining
    case "PERSONAL_CARE_AND_SERVICES": self = .personalCareAndServices
    case "PROTECTIVE_SERVICES": self = .protectiveServices
    case "REAL_ESTATE": self = .realEstate
    case "RESTAURANT_AND_HOSPITALITY": self = .restaurantAndHospitality
    case "SALES_AND_RETAIL": self = .salesAndRetail
    case "SCIENCE_AND_ENGINEERING": self = .scienceAndEngineering
    case "SOCIAL_SERVICES_AND_NON_PROFIT": self = .socialServicesAndNonProfit
    case "SPORTS_FITNESS_AND_RECREATION": self = .sportsFitnessAndRecreation
    case "TRANSPORTATION_AND_LOGISTICS": self = .transportationAndLogistics
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .accountingAndFinance
    case 2: self = .administrativeAndOffice
    case 3: self = .advertisingAndMarketing
    case 4: self = .animalCare
    case 5: self = .artFashionAndDesign
    case 6: self = .businessOperations
    case 7: self = .cleaningAndFacilities
    case 8: self = .computerAndIt
    case 9: self = .construction
    case 10: self = .customerService
    case 11: self = .education
    case 12: self = .entertainmentAndTravel
    case 13: self = .farmingAndOutdoors
    case 14: self = .healthcare
    case 15: self = .humanResources
    case 16: self = .installationMaintenanceAndRepair
    case 17: self = .legal
    case 18: self = .management
    case 19: self = .manufacturingAndWarehouse
    case 20: self = .mediaCommunicationsAndWriting
    case 21: self = .oilGasAndMining
    case 22: self = .personalCareAndServices
    case 23: self = .protectiveServices
    case 24: self = .realEstate
    case 25: self = .restaurantAndHospitality
    case 26: self = .salesAndRetail
    case 27: self = .scienceAndEngineering
    case 28: self = .socialServicesAndNonProfit
    case 29: self = .sportsFitnessAndRecreation
    case 30: self = .transportationAndLogistics
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .accountingAndFinance: return try container.encode(1)
    case .administrativeAndOffice: return try container.encode(2)
    case .advertisingAndMarketing: return try container.encode(3)
    case .animalCare: return try container.encode(4)
    case .artFashionAndDesign: return try container.encode(5)
    case .businessOperations: return try container.encode(6)
    case .cleaningAndFacilities: return try container.encode(7)
    case .computerAndIt: return try container.encode(8)
    case .construction: return try container.encode(9)
    case .customerService: return try container.encode(10)
    case .education: return try container.encode(11)
    case .entertainmentAndTravel: return try container.encode(12)
    case .farmingAndOutdoors: return try container.encode(13)
    case .healthcare: return try container.encode(14)
    case .humanResources: return try container.encode(15)
    case .installationMaintenanceAndRepair: return try container.encode(16)
    case .legal: return try container.encode(17)
    case .management: return try container.encode(18)
    case .manufacturingAndWarehouse: return try container.encode(19)
    case .mediaCommunicationsAndWriting: return try container.encode(20)
    case .oilGasAndMining: return try container.encode(21)
    case .personalCareAndServices: return try container.encode(22)
    case .protectiveServices: return try container.encode(23)
    case .realEstate: return try container.encode(24)
    case .restaurantAndHospitality: return try container.encode(25)
    case .salesAndRetail: return try container.encode(26)
    case .scienceAndEngineering: return try container.encode(27)
    case .socialServicesAndNonProfit: return try container.encode(28)
    case .sportsFitnessAndRecreation: return try container.encode(29)
    case .transportationAndLogistics: return try container.encode(30)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
