// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An event issued when a job seeker interacts with the application that
/// implements Cloud Talent Solution.
public struct JobEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The type of the event (see
  /// [JobEventType][google.cloud.talent.v4.JobEvent.JobEventType]).
  ///
  /// [google.cloud.talent.v4.JobEvent.JobEventType]: <doc:JobEvent/JobEventType>
  public var type: JobEvent.JobEventType = JobEvent.JobEventType()

  /// Required. The [job name(s)][google.cloud.talent.v4.Job.name] associated
  /// with this event. For example, if this is an
  /// [impression][google.cloud.talent.v4.JobEvent.JobEventType.IMPRESSION]
  /// event, this field contains the identifiers of all jobs shown to the job
  /// seeker. If this was a
  /// [view][google.cloud.talent.v4.JobEvent.JobEventType.VIEW] event, this field
  /// contains the identifier of the viewed job.
  ///
  /// The format is
  /// "projects/{project_id}/tenants/{tenant_id}/jobs/{job_id}", for
  /// example, "projects/foo/tenants/bar/jobs/baz".
  ///
  /// [google.cloud.talent.v4.Job.name]: <doc:Job/name>
  /// [google.cloud.talent.v4.JobEvent.JobEventType.IMPRESSION]: <doc:JobEvent/JobEventType/impression>
  /// [google.cloud.talent.v4.JobEvent.JobEventType.VIEW]: <doc:JobEvent/JobEventType/view>
  public var jobs: [Swift.String] = []

  /// Initialize a new instance of `JobEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobEvent().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An enumeration of an event attributed to the behavior of the end user,
  /// such as a job seeker.
  public enum JobEventType: Codable, Equatable, Sendable {
    /// The event is unspecified by other provided values.
    case unspecified
    /// The job seeker or other entity interacting with the service has
    /// had a job rendered in their view, such as in a list of search results in
    /// a compressed or clipped format. This event is typically associated with
    /// the viewing of a jobs list on a single page by a job seeker.
    case impression
    /// The job seeker, or other entity interacting with the service, has
    /// viewed the details of a job, including the full description. This
    /// event doesn't apply to the viewing a snippet of a job appearing as a
    /// part of the job search results. Viewing a snippet is associated with an
    /// [impression][google.cloud.talent.v4.JobEvent.JobEventType.IMPRESSION]).
    ///
    /// [google.cloud.talent.v4.JobEvent.JobEventType.IMPRESSION]: <doc:JobEvent/JobEventType/impression>
    case view
    /// The job seeker or other entity interacting with the service
    /// performed an action to view a job and was redirected to a different
    /// website for job.
    case viewRedirect
    /// The job seeker or other entity interacting with the service
    /// began the process or demonstrated the intention of applying for a job.
    case applicationStart
    /// The job seeker or other entity interacting with the service
    /// submitted an application for a job.
    case applicationFinish
    /// The job seeker or other entity interacting with the service
    /// submitted an application for a job with a single click without
    /// entering information. If a job seeker performs this action, send only
    /// this event to the service. Do not also send
    /// [JobEventType.APPLICATION_START][google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_START]
    /// or
    /// [JobEventType.APPLICATION_FINISH][google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_FINISH]
    /// events.
    ///
    /// [google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_FINISH]: <doc:JobEvent/JobEventType/applicationFinish>
    /// [google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_START]: <doc:JobEvent/JobEventType/applicationStart>
    case applicationQuickSubmission
    /// The job seeker or other entity interacting with the service
    /// performed an action to apply to a job and was redirected to a different
    /// website to complete the application.
    case applicationRedirect
    /// The job seeker or other entity interacting with the service began the
    /// process or demonstrated the intention of applying for a job from the
    /// search results page without viewing the details of the job posting.
    /// If sending this event, JobEventType.VIEW event shouldn't be sent.
    case applicationStartFromSearch
    /// The job seeker, or other entity interacting with the service, performs an
    /// action with a single click from the search results page to apply to a job
    /// (without viewing the details of the job posting), and is redirected
    /// to a different website to complete the application. If a candidate
    /// performs this action, send only this event to the service. Do not also
    /// send
    /// [JobEventType.APPLICATION_START][google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_START],
    /// [JobEventType.APPLICATION_FINISH][google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_FINISH]
    /// or [JobEventType.VIEW][google.cloud.talent.v4.JobEvent.JobEventType.VIEW]
    /// events.
    ///
    /// [google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_FINISH]: <doc:JobEvent/JobEventType/applicationFinish>
    /// [google.cloud.talent.v4.JobEvent.JobEventType.APPLICATION_START]: <doc:JobEvent/JobEventType/applicationStart>
    /// [google.cloud.talent.v4.JobEvent.JobEventType.VIEW]: <doc:JobEvent/JobEventType/view>
    case applicationRedirectFromSearch
    /// This event should be used when a company submits an application
    /// on behalf of a job seeker. This event is intended for use by staffing
    /// agencies attempting to place candidates.
    case applicationCompanySubmit
    /// The job seeker or other entity interacting with the service demonstrated
    /// an interest in a job by bookmarking or saving it.
    case bookmark
    /// The job seeker or other entity interacting with the service was
    /// sent a notification, such as an email alert or device notification,
    /// containing one or more jobs listings generated by the service.
    case notification
    /// The job seeker or other entity interacting with the service was
    /// employed by the hiring entity (employer). Send this event
    /// only if the job seeker was hired through an application that was
    /// initiated by a search conducted through the Cloud Talent Solution
    /// service.
    case hired
    /// A recruiter or staffing agency submitted an application on behalf of the
    /// candidate after interacting with the service to identify a suitable job
    /// posting.
    case sentCv
    /// The entity interacting with the service (for example, the job seeker),
    /// was granted an initial interview by the hiring entity (employer). This
    /// event should only be sent if the job seeker was granted an interview as
    /// part of an application that was initiated by a search conducted through /
    /// recommendation provided by the Cloud Talent Solution service.
    case interviewGranted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .impression: return 1
      case .view: return 2
      case .viewRedirect: return 3
      case .applicationStart: return 4
      case .applicationFinish: return 5
      case .applicationQuickSubmission: return 6
      case .applicationRedirect: return 7
      case .applicationStartFromSearch: return 8
      case .applicationRedirectFromSearch: return 9
      case .applicationCompanySubmit: return 10
      case .bookmark: return 11
      case .notification: return 12
      case .hired: return 13
      case .sentCv: return 14
      case .interviewGranted: return 15
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "JOB_EVENT_TYPE_UNSPECIFIED"
      case .impression: return "IMPRESSION"
      case .view: return "VIEW"
      case .viewRedirect: return "VIEW_REDIRECT"
      case .applicationStart: return "APPLICATION_START"
      case .applicationFinish: return "APPLICATION_FINISH"
      case .applicationQuickSubmission: return "APPLICATION_QUICK_SUBMISSION"
      case .applicationRedirect: return "APPLICATION_REDIRECT"
      case .applicationStartFromSearch: return "APPLICATION_START_FROM_SEARCH"
      case .applicationRedirectFromSearch: return "APPLICATION_REDIRECT_FROM_SEARCH"
      case .applicationCompanySubmit: return "APPLICATION_COMPANY_SUBMIT"
      case .bookmark: return "BOOKMARK"
      case .notification: return "NOTIFICATION"
      case .hired: return "HIRED"
      case .sentCv: return "SENT_CV"
      case .interviewGranted: return "INTERVIEW_GRANTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "JOB_EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "IMPRESSION": self = .impression
      case "VIEW": self = .view
      case "VIEW_REDIRECT": self = .viewRedirect
      case "APPLICATION_START": self = .applicationStart
      case "APPLICATION_FINISH": self = .applicationFinish
      case "APPLICATION_QUICK_SUBMISSION": self = .applicationQuickSubmission
      case "APPLICATION_REDIRECT": self = .applicationRedirect
      case "APPLICATION_START_FROM_SEARCH": self = .applicationStartFromSearch
      case "APPLICATION_REDIRECT_FROM_SEARCH": self = .applicationRedirectFromSearch
      case "APPLICATION_COMPANY_SUBMIT": self = .applicationCompanySubmit
      case "BOOKMARK": self = .bookmark
      case "NOTIFICATION": self = .notification
      case "HIRED": self = .hired
      case "SENT_CV": self = .sentCv
      case "INTERVIEW_GRANTED": self = .interviewGranted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .impression
      case 2: self = .view
      case 3: self = .viewRedirect
      case 4: self = .applicationStart
      case 5: self = .applicationFinish
      case 6: self = .applicationQuickSubmission
      case 7: self = .applicationRedirect
      case 8: self = .applicationStartFromSearch
      case 9: self = .applicationRedirectFromSearch
      case 10: self = .applicationCompanySubmit
      case 11: self = .bookmark
      case 12: self = .notification
      case 13: self = .hired
      case 14: self = .sentCv
      case 15: self = .interviewGranted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .impression: return try container.encode(1)
      case .view: return try container.encode(2)
      case .viewRedirect: return try container.encode(3)
      case .applicationStart: return try container.encode(4)
      case .applicationFinish: return try container.encode(5)
      case .applicationQuickSubmission: return try container.encode(6)
      case .applicationRedirect: return try container.encode(7)
      case .applicationStartFromSearch: return try container.encode(8)
      case .applicationRedirectFromSearch: return try container.encode(9)
      case .applicationCompanySubmit: return try container.encode(10)
      case .bookmark: return try container.encode(11)
      case .notification: return try container.encode(12)
      case .hired: return try container.encode(13)
      case .sentCv: return try container.encode(14)
      case .interviewGranted: return try container.encode(15)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.JobEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
