// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An enum that represents the required experience level required for the job.
public enum JobLevel: Codable, Equatable, Sendable {
  /// The default value if the level isn't specified.
  case unspecified
  /// Entry-level individual contributors, typically with less than 2 years of
  /// experience in a similar role. Includes interns.
  case entryLevel
  /// Experienced individual contributors, typically with 2+ years of
  /// experience in a similar role.
  case experienced
  /// Entry- to mid-level managers responsible for managing a team of people.
  case manager
  /// Senior-level managers responsible for managing teams of managers.
  case director
  /// Executive-level managers and above, including C-level positions.
  case executive
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .entryLevel: return 1
    case .experienced: return 2
    case .manager: return 3
    case .director: return 4
    case .executive: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "JOB_LEVEL_UNSPECIFIED"
    case .entryLevel: return "ENTRY_LEVEL"
    case .experienced: return "EXPERIENCED"
    case .manager: return "MANAGER"
    case .director: return "DIRECTOR"
    case .executive: return "EXECUTIVE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "JOB_LEVEL_UNSPECIFIED": self = .unspecified
    case "ENTRY_LEVEL": self = .entryLevel
    case "EXPERIENCED": self = .experienced
    case "MANAGER": self = .manager
    case "DIRECTOR": self = .director
    case "EXECUTIVE": self = .executive
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .entryLevel
    case 2: self = .experienced
    case 3: self = .manager
    case 4: self = .director
    case 5: self = .executive
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .entryLevel: return try container.encode(1)
    case .experienced: return try container.encode(2)
    case .manager: return try container.encode(3)
    case .director: return try container.encode(4)
    case .executive: return try container.encode(5)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
