// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The query required to perform a search query.
public struct JobQuery: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The query string that matches against the job title, description, and
  /// location fields.
  ///
  /// The maximum number of allowed characters is 255.
  public var query: Swift.String = Swift.String()

  /// The language code of [query][google.cloud.talent.v4.JobQuery.query]. For
  /// example, "en-US". This field helps to better interpret the query.
  ///
  /// If a value isn't specified, the query language code is automatically
  /// detected, which may not be accurate.
  ///
  /// Language code should be in BCP-47 format, such as "en-US" or "sr-Latn".
  /// For more information, see
  /// [Tags for Identifying Languages](https://tools.ietf.org/html/bcp47).
  ///
  /// [google.cloud.talent.v4.JobQuery.query]: <doc:JobQuery/query>
  public var queryLanguageCode: Swift.String = Swift.String()

  /// This filter specifies the company entities to search against.
  ///
  /// If a value isn't specified, jobs are searched for against all
  /// companies.
  ///
  /// If multiple values are specified, jobs are searched against the
  /// companies specified.
  ///
  /// The format is
  /// "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}". For
  /// example, "projects/foo/tenants/bar/companies/baz".
  ///
  /// At most 20 company filters are allowed.
  public var companies: [Swift.String] = []

  /// The location filter specifies geo-regions containing the jobs to
  /// search against. See [LocationFilter][google.cloud.talent.v4.LocationFilter]
  /// for more information.
  ///
  /// If a location value isn't specified, jobs fitting the other search
  /// criteria are retrieved regardless of where they're located.
  ///
  /// If multiple values are specified, jobs are retrieved from any of the
  /// specified locations. If different values are specified for the
  /// [LocationFilter.distance_in_miles][google.cloud.talent.v4.LocationFilter.distance_in_miles]
  /// parameter, the maximum provided distance is used for all locations.
  ///
  /// At most 5 location filters are allowed.
  ///
  /// [google.cloud.talent.v4.LocationFilter]: <doc:LocationFilter>
  /// [google.cloud.talent.v4.LocationFilter.distance_in_miles]: <doc:LocationFilter/distanceInMiles>
  public var locationFilters: [LocationFilter] = []

  /// The category filter specifies the categories of jobs to search against.
  /// See [JobCategory][google.cloud.talent.v4.JobCategory] for more information.
  ///
  /// If a value isn't specified, jobs from any category are searched against.
  ///
  /// If multiple values are specified, jobs from any of the specified
  /// categories are searched against.
  ///
  /// [google.cloud.talent.v4.JobCategory]: <doc:JobCategory>
  public var jobCategories: [JobCategory] = []

  /// Allows filtering jobs by commute time with different travel methods (for
  ///  example, driving or public transit).
  ///
  /// Note: This only works when you specify a
  /// [CommuteMethod][google.cloud.talent.v4.CommuteMethod]. In this case,
  /// [location_filters][google.cloud.talent.v4.JobQuery.location_filters] is
  /// ignored.
  ///
  ///  Currently we don't support sorting by commute time.
  ///
  /// [google.cloud.talent.v4.CommuteMethod]: <doc:CommuteMethod>
  /// [google.cloud.talent.v4.JobQuery.location_filters]: <doc:JobQuery/locationFilters>
  public var commuteFilter: CommuteFilter? = nil

  /// This filter specifies the company
  /// [Company.display_name][google.cloud.talent.v4.Company.display_name] of the
  /// jobs to search against. The company name must match the value exactly.
  ///
  /// Alternatively, the value being searched for can be wrapped in different
  /// match operators.
  /// `SUBSTRING_MATCH([value])`
  /// The company name must contain a case insensitive substring match of the
  /// value. Using this function may increase latency.
  ///
  /// Sample Value: `SUBSTRING_MATCH(google)`
  ///
  /// `MULTI_WORD_TOKEN_MATCH([value])`
  /// The value will be treated as a multi word token and the company name must
  /// contain a case insensitive match of the value. Using this function may
  /// increase latency.
  ///
  /// Sample Value: `MULTI_WORD_TOKEN_MATCH(google)`
  ///
  /// If a value isn't specified, jobs within the search results are
  /// associated with any company.
  ///
  /// If multiple values are specified, jobs within the search results may be
  /// associated with any of the specified companies.
  ///
  /// At most 20 company display name filters are allowed.
  ///
  /// [google.cloud.talent.v4.Company.display_name]: <doc:Company/displayName>
  public var companyDisplayNames: [Swift.String] = []

  /// This search filter is applied only to
  /// [Job.compensation_info][google.cloud.talent.v4.Job.compensation_info]. For
  /// example, if the filter is specified as "Hourly job with per-hour
  /// compensation > $15", only jobs meeting these criteria are searched. If a
  /// filter isn't defined, all open jobs are searched.
  ///
  /// [google.cloud.talent.v4.Job.compensation_info]: <doc:Job/compensationInfo>
  public var compensationFilter: CompensationFilter? = nil

  /// This filter specifies a structured syntax to match against the
  /// [Job.custom_attributes][google.cloud.talent.v4.Job.custom_attributes]
  /// marked as `filterable`.
  ///
  /// The syntax for this expression is a subset of SQL syntax.
  ///
  /// Supported operators are: `=`, `!=`, `<`, `<=`, `>`, and `>=` where the
  /// left of the operator is a custom field key and the right of the operator
  /// is a number or a quoted string. You must escape backslash (\\) and
  /// quote (\") characters.
  ///
  /// Supported functions are `LOWER([field_name])` to
  /// perform a case insensitive match and `EMPTY([field_name])` to filter on the
  /// existence of a key.
  ///
  /// Boolean expressions (AND/OR/NOT) are supported up to 3 levels of
  /// nesting (for example, "((A AND B AND C) OR NOT D) AND E"), a maximum of 100
  /// comparisons or functions are allowed in the expression. The expression
  /// must be < 10000 bytes in length.
  ///
  /// Sample Query:
  /// `(LOWER(driving_license)="class \"a\"" OR EMPTY(driving_license)) AND
  /// driving_years > 10`
  ///
  /// [google.cloud.talent.v4.Job.custom_attributes]: <doc:Job/customAttributes>
  public var customAttributeFilter: Swift.String = Swift.String()

  /// This flag controls the spell-check feature. If false, the
  /// service attempts to correct a misspelled query,
  /// for example, "enginee" is corrected to "engineer".
  ///
  /// Defaults to false: a spell check is performed.
  public var disableSpellCheck: Swift.Bool = Swift.Bool()

  /// The employment type filter specifies the employment type of jobs to
  /// search against, such as
  /// [EmploymentType.FULL_TIME][google.cloud.talent.v4.EmploymentType.FULL_TIME].
  ///
  /// If a value isn't specified, jobs in the search results includes any
  /// employment type.
  ///
  /// If multiple values are specified, jobs in the search results include
  /// any of the specified employment types.
  ///
  /// [google.cloud.talent.v4.EmploymentType.FULL_TIME]: <doc:EmploymentType/fullTime>
  public var employmentTypes: [EmploymentType] = []

  /// This filter specifies the locale of jobs to search against,
  /// for example, "en-US".
  ///
  /// If a value isn't specified, the search results can contain jobs in any
  /// locale.
  ///
  ///
  /// Language codes should be in BCP-47 format, such as "en-US" or "sr-Latn".
  /// For more information, see
  /// [Tags for Identifying Languages](https://tools.ietf.org/html/bcp47).
  ///
  /// At most 10 language code filters are allowed.
  public var languageCodes: [Swift.String] = []

  /// Jobs published within a range specified by this filter are searched
  /// against.
  public var publishTimeRange: TimestampRange? = nil

  /// This filter specifies a list of job names to be excluded during search.
  ///
  /// At most 400 excluded job names are allowed.
  public var excludedJobs: [Swift.String] = []

  /// Initialize a new instance of `JobQuery`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobQuery().with { $0.query = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.talent.v4.JobQuery"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
