// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Mutation result of a job from a batch operation.
public struct JobResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Here [Job][google.cloud.talent.v4.Job] only contains basic information
  /// including [name][google.cloud.talent.v4.Job.name],
  /// [company][google.cloud.talent.v4.Job.company],
  /// [language_code][google.cloud.talent.v4.Job.language_code] and
  /// [requisition_id][google.cloud.talent.v4.Job.requisition_id], use getJob
  /// method to retrieve detailed information of the created/updated job.
  ///
  /// [google.cloud.talent.v4.Job]: <doc:Job>
  /// [google.cloud.talent.v4.Job.company]: <doc:Job/company>
  /// [google.cloud.talent.v4.Job.language_code]: <doc:Job/languageCode>
  /// [google.cloud.talent.v4.Job.name]: <doc:Job/name>
  /// [google.cloud.talent.v4.Job.requisition_id]: <doc:Job/requisitionId>
  public var job: Job? = nil

  /// The status of the job processed. This field is populated if the
  /// processing of the [job][google.cloud.talent.v4.JobResult.job] fails.
  ///
  /// [google.cloud.talent.v4.JobResult.job]: <doc:JobResult/job>
  public var status: GoogleRpc.Status? = nil

  /// Initialize a new instance of `JobResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobResult().with { $0.job = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.JobResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
