// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class JobServiceLogging: JobServiceStub {
    let inner: any JobServiceStub
    let logger: Logger

    public init(_ inner: any JobServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-talent-v4"
      logger[metadataKey: "gcp.client.service"] = "jobs"
      logger[metadataKey: "gcp.experimental.swift.client"] = "JobService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        name: "createJob",
        action: {
          (r: CreateJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.createJob(request: r, options: o)
        })
    }

    public func batchCreateJobs(
      request: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchCreateJobs",
        action: {
          (r: BatchCreateJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchCreateJobs(request: r, options: o)
        })
    }

    public func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        name: "getJob",
        action: {
          (r: GetJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.getJob(request: r, options: o)
        })
    }

    public func updateJob(
      request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateJob",
        action: {
          (r: UpdateJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.updateJob(request: r, options: o)
        })
    }

    public func batchUpdateJobs(
      request: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchUpdateJobs",
        action: {
          (r: BatchUpdateJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchUpdateJobs(request: r, options: o)
        })
    }

    public func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteJob",
        action: { (r: DeleteJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJob(request: r, options: o)
        })
    }

    public func batchDeleteJobs(
      request: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchDeleteJobs",
        action: {
          (r: BatchDeleteJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchDeleteJobs(request: r, options: o)
        })
    }

    public func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listJobs",
        action: {
          (r: ListJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.ListJobsResponse
          in
          return try await self.inner.listJobs(request: r, options: o)
        })
    }

    public func searchJobs(
      request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchJobs",
        action: {
          (r: SearchJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.SearchJobsResponse
          in
          return try await self.inner.searchJobs(request: r, options: o)
        })
    }

    public func searchJobsForAlert(
      request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchJobsForAlert",
        action: {
          (r: SearchJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.SearchJobsResponse
          in
          return try await self.inner.searchJobsForAlert(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
