// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class JobServiceRetry: JobServiceStub {
    let inner: any JobServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any JobServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createJob(
      request: CreateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateJobRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.createJob(request: r, options: o)
        })
    }

    public func batchCreateJobs(
      request: BatchCreateJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchCreateJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchCreateJobs(request: r, options: o)
        })
    }

    public func getJob(
      request: GetJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetJobRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.getJob(request: r, options: o)
        })
    }

    public func updateJob(
      request: UpdateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateJobRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudTalentV4.Job
          in
          return try await self.inner.updateJob(request: r, options: o)
        })
    }

    public func batchUpdateJobs(
      request: BatchUpdateJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchUpdateJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchUpdateJobs(request: r, options: o)
        })
    }

    public func deleteJob(
      request: DeleteJobRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteJobRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJob(request: r, options: o)
        })
    }

    public func batchDeleteJobs(
      request: BatchDeleteJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: BatchDeleteJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.batchDeleteJobs(request: r, options: o)
        })
    }

    public func listJobs(
      request: ListJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.ListJobsResponse
          in
          return try await self.inner.listJobs(request: r, options: o)
        })
    }

    public func searchJobs(
      request: SearchJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SearchJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.SearchJobsResponse
          in
          return try await self.inner.searchJobs(request: r, options: o)
        })
    }

    public func searchJobsForAlert(
      request: SearchJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SearchJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.SearchJobsResponse
          in
          return try await self.inner.searchJobsForAlert(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
