// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// A service handles job management, including job CRUD, enumeration and search.
///
/// @Snippet(path: "JobServiceQuickstart")
public class JobServiceClient: Clients.JobServiceProtocol {
  let inner: any Clients.JobServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `JobServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.JobServiceStub = try Clients.JobServiceTransport(options)
    inner = Clients.JobServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.JobServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new job.
  ///
  /// Typically, the job becomes searchable within 10 seconds, but it may take
  /// up to 5 minutes.
  ///
  /// @Snippet(path: "JobService_CreateJob")
  public func createJob(
    request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    try await self.inner.createJob(request: request, options: options)
  }

  /// Begins executing a batch create jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchCreateJobs")
  public func batchCreateJobs(
    request: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchCreateJobs(request: request, options: options)
  }

  /// Begins executing a batch create jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchCreateJobs")
  public func batchCreateJobs(
    withPolling: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BatchCreateJobsResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try BatchCreateJobsResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.batchCreateJobs(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchCreateJobsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Retrieves the specified job, whose status is OPEN or recently EXPIRED
  /// within the last 90 days.
  ///
  /// @Snippet(path: "JobService_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Updates specified job.
  ///
  /// Typically, updated contents become visible in search results within 10
  /// seconds, but it may take up to 5 minutes.
  ///
  /// @Snippet(path: "JobService_UpdateJob")
  public func updateJob(
    request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    try await self.inner.updateJob(request: request, options: options)
  }

  /// Begins executing a batch update jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchUpdateJobs")
  public func batchUpdateJobs(
    request: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchUpdateJobs(request: request, options: options)
  }

  /// Begins executing a batch update jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchUpdateJobs")
  public func batchUpdateJobs(
    withPolling: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BatchUpdateJobsResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try BatchUpdateJobsResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.batchUpdateJobs(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchUpdateJobsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified job.
  ///
  /// Typically, the job becomes unsearchable within 10 seconds, but it may take
  /// up to 5 minutes.
  ///
  /// @Snippet(path: "JobService_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Begins executing a batch delete jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchDeleteJobs")
  public func batchDeleteJobs(
    request: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchDeleteJobs(request: request, options: options)
  }

  /// Begins executing a batch delete jobs operation.
  ///
  /// @Snippet(path: "JobService_BatchDeleteJobs")
  public func batchDeleteJobs(
    withPolling: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BatchDeleteJobsResponse>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try BatchDeleteJobsResponse(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.batchDeleteJobs(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchDeleteJobsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists jobs by filter.
  ///
  /// @Snippet(path: "JobService_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// Lists jobs by filter.
  ///
  /// @Snippet(path: "JobService_ListJobs")
  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudTalentV4.ListJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Searches for jobs using the provided
  /// [SearchJobsRequest][google.cloud.talent.v4.SearchJobsRequest].
  ///
  /// This call constrains the
  /// [visibility][google.cloud.talent.v4.Job.visibility] of jobs present in the
  /// database, and only returns jobs that the caller has permission to search
  /// against.
  ///
  /// [google.cloud.talent.v4.Job.visibility]: <doc:Job/visibility>
  /// [google.cloud.talent.v4.SearchJobsRequest]: <doc:SearchJobsRequest>
  ///
  /// @Snippet(path: "JobService_SearchJobs")
  public func searchJobs(
    request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
    try await self.inner.searchJobs(request: request, options: options)
  }

  /// Searches for jobs using the provided
  /// [SearchJobsRequest][google.cloud.talent.v4.SearchJobsRequest].
  ///
  /// This API call is intended for the use case of targeting passive job
  /// seekers (for example, job seekers who have signed up to receive email
  /// alerts about potential job opportunities), it has different algorithmic
  /// adjustments that are designed to specifically target passive job seekers.
  ///
  /// This call constrains the
  /// [visibility][google.cloud.talent.v4.Job.visibility] of jobs present in the
  /// database, and only returns jobs the caller has permission to search
  /// against.
  ///
  /// [google.cloud.talent.v4.Job.visibility]: <doc:Job/visibility>
  /// [google.cloud.talent.v4.SearchJobsRequest]: <doc:SearchJobsRequest>
  ///
  /// @Snippet(path: "JobService_SearchJobsForAlert")
  public func searchJobsForAlert(
    request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
    try await self.inner.searchJobsForAlert(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `JobServiceClient`.
  ///
  /// To mock `JobServiceClient` change your functions to receive
  /// `some JobServiceProtocol` or `any JobServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol JobServiceProtocol {
    /// See `JobServiceClient.createJob`.
    func createJob(request: CreateJobRequest) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.createJob`.
    func createJob(
      parent: Swift.String,
      job: Job?,
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.batchCreateJobs`.
    func batchCreateJobs(request: BatchCreateJobsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchCreateJobs`.
    func batchCreateJobs(withPolling: BatchCreateJobsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<BatchCreateJobsResponse>

    /// See `JobServiceClient.batchCreateJobs`.
    func batchCreateJobs(
      parent: Swift.String,
      jobs: [Job],
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse>

    /// See `JobServiceClient.getJob`.
    func getJob(request: GetJobRequest) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.getJob`.
    func getJob(
      name: Swift.String,
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.updateJob`.
    func updateJob(request: UpdateJobRequest) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.updateJob`.
    func updateJob(
      job: Job?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.batchUpdateJobs`.
    func batchUpdateJobs(request: BatchUpdateJobsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchUpdateJobs`.
    func batchUpdateJobs(withPolling: BatchUpdateJobsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<BatchUpdateJobsResponse>

    /// See `JobServiceClient.batchUpdateJobs`.
    func batchUpdateJobs(
      parent: Swift.String,
      jobs: [Job],
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse>

    /// See `JobServiceClient.deleteJob`.
    func deleteJob(request: DeleteJobRequest) async throws

    /// See `JobServiceClient.deleteJob`.
    func deleteJob(
      name: Swift.String,
    ) async throws

    /// See `JobServiceClient.batchDeleteJobs`.
    func batchDeleteJobs(request: BatchDeleteJobsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchDeleteJobs`.
    func batchDeleteJobs(withPolling: BatchDeleteJobsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<BatchDeleteJobsResponse>

    /// See `JobServiceClient.batchDeleteJobs`.
    func batchDeleteJobs(
      parent: Swift.String,
      names: [Swift.String],
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse>

    /// See `JobServiceClient.listJobs`.
    func listJobs(request: ListJobsRequest) async throws -> GoogleCloudTalentV4.ListJobsResponse

    /// See `JobServiceClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobServiceClient.listJobs`.
    func listJobs(
      parent: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobServiceClient.searchJobs`.
    func searchJobs(request: SearchJobsRequest) async throws
      -> GoogleCloudTalentV4.SearchJobsResponse

    /// See `JobServiceClient.searchJobsForAlert`.
    func searchJobsForAlert(request: SearchJobsRequest) async throws
      -> GoogleCloudTalentV4.SearchJobsResponse

    /// See `JobServiceClient.createJob`.
    func createJob(
      request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.batchCreateJobs`.
    func batchCreateJobs(
      request: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchCreateJobs`.
    func batchCreateJobs(
      withPolling: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse>

    /// See `JobServiceClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.updateJob`.
    func updateJob(
      request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Job

    /// See `JobServiceClient.batchUpdateJobs`.
    func batchUpdateJobs(
      request: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchUpdateJobs`.
    func batchUpdateJobs(
      withPolling: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse>

    /// See `JobServiceClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `JobServiceClient.batchDeleteJobs`.
    func batchDeleteJobs(
      request: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `JobServiceClient.batchDeleteJobs`.
    func batchDeleteJobs(
      withPolling: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse>

    /// See `JobServiceClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListJobsResponse

    /// See `JobServiceClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobServiceClient.searchJobs`.
    func searchJobs(
      request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse

    /// See `JobServiceClient.searchJobsForAlert`.
    func searchJobsForAlert(
      request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.SearchJobsResponse
  }
}

// Default implementations
extension Clients.JobServiceProtocol {
  public func createJob(request: CreateJobRequest) async throws -> GoogleCloudTalentV4.Job {
    try await self.createJob(request: request, options: .init())
  }

  public func createJob(
    request: CreateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createJob(
    parent: Swift.String,
    job: Job?,
  ) async throws -> GoogleCloudTalentV4.Job {
    let request = CreateJobRequest().with {
      $0.parent = parent
      $0.job = job
    }
    return try await self.createJob(request: request)
  }

  public func batchCreateJobs(request: BatchCreateJobsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchCreateJobs(request: request, options: .init())
  }

  public func batchCreateJobs(
    request: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchCreateJobs(withPolling: BatchCreateJobsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse>
  {
    try await self.batchCreateJobs(withPolling: withPolling, options: .init())
  }

  public func batchCreateJobs(
    withPolling: BatchCreateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchCreateJobsResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchCreateJobs(
    parent: Swift.String,
    jobs: [Job],
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchCreateJobsResponse> {
    let request = BatchCreateJobsRequest().with {
      $0.parent = parent
      $0.jobs = jobs
    }
    return try await self.batchCreateJobs(withPolling: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudTalentV4.Job {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getJob(
    name: Swift.String,
  ) async throws -> GoogleCloudTalentV4.Job {
    let request = GetJobRequest().with {
      $0.name = name
    }
    return try await self.getJob(request: request)
  }

  public func updateJob(request: UpdateJobRequest) async throws -> GoogleCloudTalentV4.Job {
    try await self.updateJob(request: request, options: .init())
  }

  public func updateJob(
    request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateJob(
    job: Job?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudTalentV4.Job {
    let request = UpdateJobRequest().with {
      $0.job = job
      $0.updateMask = updateMask
    }
    return try await self.updateJob(request: request)
  }

  public func batchUpdateJobs(request: BatchUpdateJobsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchUpdateJobs(request: request, options: .init())
  }

  public func batchUpdateJobs(
    request: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchUpdateJobs(withPolling: BatchUpdateJobsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse>
  {
    try await self.batchUpdateJobs(withPolling: withPolling, options: .init())
  }

  public func batchUpdateJobs(
    withPolling: BatchUpdateJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchUpdateJobsResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchUpdateJobs(
    parent: Swift.String,
    jobs: [Job],
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchUpdateJobsResponse> {
    let request = BatchUpdateJobsRequest().with {
      $0.parent = parent
      $0.jobs = jobs
    }
    return try await self.batchUpdateJobs(withPolling: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteJob(
    name: Swift.String,
  ) async throws {
    let request = DeleteJobRequest().with {
      $0.name = name
    }
    try await self.deleteJob(request: request)
  }

  public func batchDeleteJobs(request: BatchDeleteJobsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchDeleteJobs(request: request, options: .init())
  }

  public func batchDeleteJobs(
    request: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchDeleteJobs(withPolling: BatchDeleteJobsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse>
  {
    try await self.batchDeleteJobs(withPolling: withPolling, options: .init())
  }

  public func batchDeleteJobs(
    withPolling: BatchDeleteJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchDeleteJobsResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchDeleteJobs(
    parent: Swift.String,
    names: [Swift.String],
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchDeleteJobsResponse> {
    let request = BatchDeleteJobsRequest().with {
      $0.parent = parent
      $0.names = names
    }
    return try await self.batchDeleteJobs(withPolling: request)
  }

  public func listJobs(request: ListJobsRequest) async throws
    -> GoogleCloudTalentV4.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.ListJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listJobs(
    byItem: ListJobsRequest
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    try self.listJobs(byItem: byItem, options: .init())
  }

  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudTalentV4.ListJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobs(
    parent: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.parent = parent
      $0.filter = filter
    }
    return try self.listJobs(byItem: request)
  }

  public func searchJobs(request: SearchJobsRequest) async throws
    -> GoogleCloudTalentV4.SearchJobsResponse
  {
    try await self.searchJobs(request: request, options: .init())
  }

  public func searchJobs(
    request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchJobsForAlert(request: SearchJobsRequest) async throws
    -> GoogleCloudTalentV4.SearchJobsResponse
  {
    try await self.searchJobsForAlert(request: request, options: .init())
  }

  public func searchJobsForAlert(
    request: SearchJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.SearchJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
