// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// An enum that specifies the job attributes that are returned in the
/// [MatchingJob.job][google.cloud.talent.v4.SearchJobsResponse.MatchingJob.job]
/// or [ListJobsResponse.jobs][google.cloud.talent.v4.ListJobsResponse.jobs]
/// fields.
///
/// [google.cloud.talent.v4.ListJobsResponse.jobs]: <doc:ListJobsResponse/jobs>
/// [google.cloud.talent.v4.SearchJobsResponse.MatchingJob.job]: <doc:SearchJobsResponse/MatchingJob/job>
public enum JobView: Codable, Equatable, Sendable {
  /// Default value.
  case unspecified
  /// A ID only view of job, with following attributes:
  /// [Job.name][google.cloud.talent.v4.Job.name],
  /// [Job.requisition_id][google.cloud.talent.v4.Job.requisition_id],
  /// [Job.language_code][google.cloud.talent.v4.Job.language_code].
  ///
  /// [google.cloud.talent.v4.Job.language_code]: <doc:Job/languageCode>
  /// [google.cloud.talent.v4.Job.name]: <doc:Job/name>
  /// [google.cloud.talent.v4.Job.requisition_id]: <doc:Job/requisitionId>
  case idOnly
  /// A minimal view of the job, with the following attributes:
  /// [Job.name][google.cloud.talent.v4.Job.name],
  /// [Job.requisition_id][google.cloud.talent.v4.Job.requisition_id],
  /// [Job.title][google.cloud.talent.v4.Job.title],
  /// [Job.company][google.cloud.talent.v4.Job.company],
  /// [Job.DerivedInfo.locations][google.cloud.talent.v4.Job.DerivedInfo.locations],
  /// [Job.language_code][google.cloud.talent.v4.Job.language_code].
  ///
  /// [google.cloud.talent.v4.Job.DerivedInfo.locations]: <doc:Job/DerivedInfo/locations>
  /// [google.cloud.talent.v4.Job.company]: <doc:Job/company>
  /// [google.cloud.talent.v4.Job.language_code]: <doc:Job/languageCode>
  /// [google.cloud.talent.v4.Job.name]: <doc:Job/name>
  /// [google.cloud.talent.v4.Job.requisition_id]: <doc:Job/requisitionId>
  /// [google.cloud.talent.v4.Job.title]: <doc:Job/title>
  case minimal
  /// A small view of the job, with the following attributes in the search
  /// results: [Job.name][google.cloud.talent.v4.Job.name],
  /// [Job.requisition_id][google.cloud.talent.v4.Job.requisition_id],
  /// [Job.title][google.cloud.talent.v4.Job.title],
  /// [Job.company][google.cloud.talent.v4.Job.company],
  /// [Job.DerivedInfo.locations][google.cloud.talent.v4.Job.DerivedInfo.locations],
  /// [Job.visibility][google.cloud.talent.v4.Job.visibility],
  /// [Job.language_code][google.cloud.talent.v4.Job.language_code],
  /// [Job.description][google.cloud.talent.v4.Job.description].
  ///
  /// [google.cloud.talent.v4.Job.DerivedInfo.locations]: <doc:Job/DerivedInfo/locations>
  /// [google.cloud.talent.v4.Job.company]: <doc:Job/company>
  /// [google.cloud.talent.v4.Job.description]: <doc:Job/description>
  /// [google.cloud.talent.v4.Job.language_code]: <doc:Job/languageCode>
  /// [google.cloud.talent.v4.Job.name]: <doc:Job/name>
  /// [google.cloud.talent.v4.Job.requisition_id]: <doc:Job/requisitionId>
  /// [google.cloud.talent.v4.Job.title]: <doc:Job/title>
  /// [google.cloud.talent.v4.Job.visibility]: <doc:Job/visibility>
  case small
  /// All available attributes are included in the search results.
  case full
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .idOnly: return 1
    case .minimal: return 2
    case .small: return 3
    case .full: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "JOB_VIEW_UNSPECIFIED"
    case .idOnly: return "JOB_VIEW_ID_ONLY"
    case .minimal: return "JOB_VIEW_MINIMAL"
    case .small: return "JOB_VIEW_SMALL"
    case .full: return "JOB_VIEW_FULL"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobView/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "JOB_VIEW_UNSPECIFIED": self = .unspecified
    case "JOB_VIEW_ID_ONLY": self = .idOnly
    case "JOB_VIEW_MINIMAL": self = .minimal
    case "JOB_VIEW_SMALL": self = .small
    case "JOB_VIEW_FULL": self = .full
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobView/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .idOnly
    case 2: self = .minimal
    case 3: self = .small
    case 4: self = .full
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .idOnly: return try container.encode(1)
    case .minimal: return try container.encode(2)
    case .small: return try container.encode(3)
    case .full: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
