// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// List companies for which the client has ACL visibility.
public struct ListCompaniesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the tenant under which the company is created.
  ///
  /// The format is "projects/{project_id}/tenants/{tenant_id}", for example,
  /// "projects/foo/tenants/bar".
  public var parent: Swift.String = Swift.String()

  /// The starting indicator from which to return results.
  public var pageToken: Swift.String = Swift.String()

  /// The maximum number of companies to be returned, at most 100.
  /// Default is 100 if a non-positive number is provided.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Set to true if the companies requested must have open jobs.
  ///
  /// Defaults to false.
  ///
  /// If true, at most
  /// [page_size][google.cloud.talent.v4.ListCompaniesRequest.page_size] of
  /// companies are fetched, among which only those with open jobs are returned.
  ///
  /// [google.cloud.talent.v4.ListCompaniesRequest.page_size]: <doc:ListCompaniesRequest/pageSize>
  public var requireOpenJobs: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListCompaniesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCompaniesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let requireOpenJobs = CodingKeys(stringValue: "requireOpenJobs")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageToken",
      "pageSize",
      "requireOpenJobs",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requireOpenJobs) {
      self.requireOpenJobs = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.requireOpenJobs, forKey: .requireOpenJobs)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.ListCompaniesRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
