// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Geographic region of the search.
public struct LocationFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The address name, such as "Mountain View" or "Bay Area".
  public var address: Swift.String = Swift.String()

  /// CLDR region code of the country/region. This field may be used in two ways:
  ///
  /// 1) If telecommute preference is not set, this field is used address
  /// ambiguity of the user-input address. For example, "Liverpool" may refer to
  /// "Liverpool, NY, US" or "Liverpool, UK". This region code biases the
  /// address resolution toward a specific country or territory. If this field is
  /// not set, address resolution is biased toward the United States by default.
  ///
  /// 2) If telecommute preference is set to TELECOMMUTE_ALLOWED, the
  /// telecommute location filter will be limited to the region specified in this
  /// field. If this field is not set, the telecommute job locations will not be
  ///
  /// See
  /// https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_information.html
  /// for details. Example: "CH" for Switzerland.
  public var regionCode: Swift.String = Swift.String()

  /// The latitude and longitude of the geographic center to search from. This
  /// field is ignored if `address` is provided.
  public var latLng: GoogleType.LatLng? = nil

  /// The distance_in_miles is applied when the location being searched for is
  /// identified as a city or smaller. This field is ignored if the location
  /// being searched for is a state or larger.
  public var distanceInMiles: Swift.Double = Swift.Double()

  /// Allows the client to return jobs without a
  /// set location, specifically, telecommuting jobs (telecommuting is considered
  /// by the service as a special location).
  /// [Job.posting_region][google.cloud.talent.v4.Job.posting_region] indicates
  /// if a job permits telecommuting. If this field is set to
  /// [TelecommutePreference.TELECOMMUTE_ALLOWED][google.cloud.talent.v4.LocationFilter.TelecommutePreference.TELECOMMUTE_ALLOWED],
  /// telecommuting jobs are searched, and
  /// [address][google.cloud.talent.v4.LocationFilter.address] and
  /// [lat_lng][google.cloud.talent.v4.LocationFilter.lat_lng] are ignored. If
  /// not set or set to
  /// [TelecommutePreference.TELECOMMUTE_EXCLUDED][google.cloud.talent.v4.LocationFilter.TelecommutePreference.TELECOMMUTE_EXCLUDED],
  /// the telecommute status of the jobs is ignored. Jobs that have
  /// [PostingRegion.TELECOMMUTE][google.cloud.talent.v4.PostingRegion.TELECOMMUTE]
  /// and have additional [Job.addresses][google.cloud.talent.v4.Job.addresses]
  /// may still be matched based on other location filters using
  /// [address][google.cloud.talent.v4.LocationFilter.address] or
  /// [lat_lng][google.cloud.talent.v4.LocationFilter.lat_lng].
  ///
  /// This filter can be used by itself to search exclusively for telecommuting
  /// jobs, or it can be combined with another location
  /// filter to search for a combination of job locations,
  /// such as "Mountain View" or "telecommuting" jobs. However, when used in
  /// combination with other location filters, telecommuting jobs can be
  /// treated as less relevant than other jobs in the search response.
  ///
  /// This field is only used for job search requests.
  ///
  /// [google.cloud.talent.v4.Job.addresses]: <doc:Job/addresses>
  /// [google.cloud.talent.v4.Job.posting_region]: <doc:Job/postingRegion>
  /// [google.cloud.talent.v4.LocationFilter.TelecommutePreference.TELECOMMUTE_ALLOWED]: <doc:LocationFilter/TelecommutePreference/telecommuteAllowed>
  /// [google.cloud.talent.v4.LocationFilter.TelecommutePreference.TELECOMMUTE_EXCLUDED]: <doc:LocationFilter/TelecommutePreference/telecommuteExcluded>
  /// [google.cloud.talent.v4.LocationFilter.address]: <doc:LocationFilter/address>
  /// [google.cloud.talent.v4.LocationFilter.lat_lng]: <doc:LocationFilter/latLng>
  /// [google.cloud.talent.v4.PostingRegion.TELECOMMUTE]: <doc:PostingRegion/telecommute>
  public var telecommutePreference: LocationFilter.TelecommutePreference =
    LocationFilter.TelecommutePreference()

  /// Initialize a new instance of `LocationFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LocationFilter().with { $0.address = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Specify whether to include telecommute jobs.
  public enum TelecommutePreference: Codable, Equatable, Sendable {
    /// Default value if the telecommute preference isn't specified.
    case unspecified
    /// Deprecated: Ignore telecommute status of jobs. Use
    /// TELECOMMUTE_JOBS_EXCLUDED if want to exclude telecommute jobs.
    @available(*, deprecated)
    case telecommuteExcluded
    /// Allow telecommute jobs.
    case telecommuteAllowed
    /// Exclude telecommute jobs.
    case telecommuteJobsExcluded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .telecommuteExcluded: return 1
      case .telecommuteAllowed: return 2
      case .telecommuteJobsExcluded: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "TELECOMMUTE_PREFERENCE_UNSPECIFIED"
      case .telecommuteExcluded: return "TELECOMMUTE_EXCLUDED"
      case .telecommuteAllowed: return "TELECOMMUTE_ALLOWED"
      case .telecommuteJobsExcluded: return "TELECOMMUTE_JOBS_EXCLUDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "TELECOMMUTE_PREFERENCE_UNSPECIFIED": self = .unspecified
      case "TELECOMMUTE_EXCLUDED": self = .telecommuteExcluded
      case "TELECOMMUTE_ALLOWED": self = .telecommuteAllowed
      case "TELECOMMUTE_JOBS_EXCLUDED": self = .telecommuteJobsExcluded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .telecommuteExcluded
      case 2: self = .telecommuteAllowed
      case 3: self = .telecommuteJobsExcluded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .telecommuteExcluded: return try container.encode(1)
      case .telecommuteAllowed: return try container.encode(2)
      case .telecommuteJobsExcluded: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.talent.v4.LocationFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
