// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// A resource that represents a location with full geographic information.
public struct Location: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of a location, which corresponds to the address lines field of
  /// [google.type.PostalAddress][google.type.PostalAddress]. For example,
  /// "Downtown, Atlanta, GA, USA" has a type of
  /// [LocationType.NEIGHBORHOOD][google.cloud.talent.v4.Location.LocationType.NEIGHBORHOOD],
  /// and "Kansas City, KS, USA" has a type of
  /// [LocationType.LOCALITY][google.cloud.talent.v4.Location.LocationType.LOCALITY].
  ///
  /// [google.cloud.talent.v4.Location.LocationType.LOCALITY]: <doc:Location/LocationType/locality>
  /// [google.cloud.talent.v4.Location.LocationType.NEIGHBORHOOD]: <doc:Location/LocationType/neighborhood>
  /// [google.type.PostalAddress]: https://www.google.com/search?q=Swift+google.type+GoogleType.PostalAddress
  public var locationType: Location.LocationType = Location.LocationType()

  /// Postal address of the location that includes human readable information,
  /// such as postal delivery and payments addresses. Given a postal address,
  /// a postal service can deliver items to a premises, P.O. Box, or other
  /// delivery location.
  public var postalAddress: GoogleType.PostalAddress? = nil

  /// An object representing a latitude/longitude pair.
  public var latLng: GoogleType.LatLng? = nil

  /// Radius in miles of the job location. This value is derived from the
  /// location bounding box in which a circle with the specified radius
  /// centered from [google.type.LatLng][google.type.LatLng] covers the area
  /// associated with the job location. For example, currently, "Mountain View,
  /// CA, USA" has a radius of 6.17 miles.
  ///
  /// [google.type.LatLng]: https://www.google.com/search?q=Swift+google.type+GoogleType.LatLng
  public var radiusMiles: Swift.Double = Swift.Double()

  /// Initialize a new instance of `Location`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Location().with { $0.locationType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An enum which represents the type of a location.
  public enum LocationType: Codable, Equatable, Sendable {
    /// Default value if the type isn't specified.
    case unspecified
    /// A country level location.
    case country
    /// A state or equivalent level location.
    case administrativeArea
    /// A county or equivalent level location.
    case subAdministrativeArea
    /// A city or equivalent level location.
    case locality
    /// A postal code level location.
    case postalCode
    /// A sublocality is a subdivision of a locality, for example a city borough,
    /// ward, or arrondissement. Sublocalities are usually recognized by a local
    /// political authority. For example, Manhattan and Brooklyn are recognized
    /// as boroughs by the City of New York, and are therefore modeled as
    /// sublocalities.
    case subLocality
    /// A district or equivalent level location.
    case subLocality1
    /// A smaller district or equivalent level display.
    case subLocality2
    /// A neighborhood level location.
    case neighborhood
    /// A street address level location.
    case streetAddress
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .country: return 1
      case .administrativeArea: return 2
      case .subAdministrativeArea: return 3
      case .locality: return 4
      case .postalCode: return 5
      case .subLocality: return 6
      case .subLocality1: return 7
      case .subLocality2: return 8
      case .neighborhood: return 9
      case .streetAddress: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "LOCATION_TYPE_UNSPECIFIED"
      case .country: return "COUNTRY"
      case .administrativeArea: return "ADMINISTRATIVE_AREA"
      case .subAdministrativeArea: return "SUB_ADMINISTRATIVE_AREA"
      case .locality: return "LOCALITY"
      case .postalCode: return "POSTAL_CODE"
      case .subLocality: return "SUB_LOCALITY"
      case .subLocality1: return "SUB_LOCALITY_1"
      case .subLocality2: return "SUB_LOCALITY_2"
      case .neighborhood: return "NEIGHBORHOOD"
      case .streetAddress: return "STREET_ADDRESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LocationType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "LOCATION_TYPE_UNSPECIFIED": self = .unspecified
      case "COUNTRY": self = .country
      case "ADMINISTRATIVE_AREA": self = .administrativeArea
      case "SUB_ADMINISTRATIVE_AREA": self = .subAdministrativeArea
      case "LOCALITY": self = .locality
      case "POSTAL_CODE": self = .postalCode
      case "SUB_LOCALITY": self = .subLocality
      case "SUB_LOCALITY_1": self = .subLocality1
      case "SUB_LOCALITY_2": self = .subLocality2
      case "NEIGHBORHOOD": self = .neighborhood
      case "STREET_ADDRESS": self = .streetAddress
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LocationType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .country
      case 2: self = .administrativeArea
      case 3: self = .subAdministrativeArea
      case 4: self = .locality
      case 5: self = .postalCode
      case 6: self = .subLocality
      case 7: self = .subLocality1
      case 8: self = .subLocality2
      case 9: self = .neighborhood
      case 10: self = .streetAddress
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .country: return try container.encode(1)
      case .administrativeArea: return try container.encode(2)
      case .subAdministrativeArea: return try container.encode(3)
      case .locality: return try container.encode(4)
      case .postalCode: return try container.encode(5)
      case .subLocality: return try container.encode(6)
      case .subLocality1: return try container.encode(7)
      case .subLocality2: return try container.encode(8)
      case .neighborhood: return try container.encode(9)
      case .streetAddress: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.Location"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
