// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Meta information related to the job searcher or entity
/// conducting the job search. This information is used to improve the
/// performance of the service.
public struct RequestMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required if
  /// [allow_missing_ids][google.cloud.talent.v4.RequestMetadata.allow_missing_ids]
  /// is unset or `false`.
  ///
  /// The client-defined scope or source of the service call, which typically
  /// is the domain on
  /// which the service has been implemented and is currently being run.
  ///
  /// For example, if the service is being run by client <em>Foo, Inc.</em>, on
  /// job board www.foo.com and career site www.bar.com, then this field is
  /// set to "foo.com" for use on the job board, and "bar.com" for use on the
  /// career site.
  ///
  /// Note that any improvements to the model for a particular tenant site rely
  /// on this field being set correctly to a unique domain.
  ///
  /// The maximum number of allowed characters is 255.
  ///
  /// [google.cloud.talent.v4.RequestMetadata.allow_missing_ids]: <doc:RequestMetadata/allowMissingIds>
  public var domain: Swift.String = Swift.String()

  /// Required if
  /// [allow_missing_ids][google.cloud.talent.v4.RequestMetadata.allow_missing_ids]
  /// is unset or `false`.
  ///
  /// A unique session identification string. A session is defined as the
  /// duration of an end user's interaction with the service over a certain
  /// period.
  /// Obfuscate this field for privacy concerns before
  /// providing it to the service.
  ///
  /// Note that any improvements to the model for a particular tenant site rely
  /// on this field being set correctly to a unique session ID.
  ///
  /// The maximum number of allowed characters is 255.
  ///
  /// [google.cloud.talent.v4.RequestMetadata.allow_missing_ids]: <doc:RequestMetadata/allowMissingIds>
  public var sessionId: Swift.String = Swift.String()

  /// Required if
  /// [allow_missing_ids][google.cloud.talent.v4.RequestMetadata.allow_missing_ids]
  /// is unset or `false`.
  ///
  /// A unique user identification string, as determined by the client.
  /// To have the strongest positive impact on search quality
  /// make sure the client-level is unique.
  /// Obfuscate this field for privacy concerns before
  /// providing it to the service.
  ///
  /// Note that any improvements to the model for a particular tenant site rely
  /// on this field being set correctly to a unique user ID.
  ///
  /// The maximum number of allowed characters is 255.
  ///
  /// [google.cloud.talent.v4.RequestMetadata.allow_missing_ids]: <doc:RequestMetadata/allowMissingIds>
  public var userId: Swift.String = Swift.String()

  /// Only set when any of
  /// [domain][google.cloud.talent.v4.RequestMetadata.domain],
  /// [session_id][google.cloud.talent.v4.RequestMetadata.session_id] and
  /// [user_id][google.cloud.talent.v4.RequestMetadata.user_id] isn't available
  /// for some reason. It is highly recommended not to set this field and provide
  /// accurate [domain][google.cloud.talent.v4.RequestMetadata.domain],
  /// [session_id][google.cloud.talent.v4.RequestMetadata.session_id] and
  /// [user_id][google.cloud.talent.v4.RequestMetadata.user_id] for the best
  /// service experience.
  ///
  /// [google.cloud.talent.v4.RequestMetadata.domain]: <doc:RequestMetadata/domain>
  /// [google.cloud.talent.v4.RequestMetadata.session_id]: <doc:RequestMetadata/sessionId>
  /// [google.cloud.talent.v4.RequestMetadata.user_id]: <doc:RequestMetadata/userId>
  public var allowMissingIds: Swift.Bool = Swift.Bool()

  /// The type of device used by the job seeker at the time of the call to the
  /// service.
  public var deviceInfo: DeviceInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RequestMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RequestMetadata().with { $0.domain = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let domain = CodingKeys(stringValue: "domain")
    static let sessionId = CodingKeys(stringValue: "sessionId")
    static let userId = CodingKeys(stringValue: "userId")
    static let allowMissingIds = CodingKeys(stringValue: "allowMissingIds")
    static let deviceInfo = CodingKeys(stringValue: "deviceInfo")

    static let _knownKeys: Set<Swift.String> = [
      "domain",
      "sessionId",
      "userId",
      "allowMissingIds",
      "deviceInfo",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .domain) {
      self.domain = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sessionId) {
      self.sessionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userId) {
      self.userId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissingIds) {
      self.allowMissingIds = value
    }
    self.deviceInfo = try container.decodeIfPresent(DeviceInfo.self, forKey: .deviceInfo)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.domain, forKey: .domain)
    try container.encode(self.sessionId, forKey: .sessionId)
    try container.encode(self.userId, forKey: .userId)
    try container.encode(self.allowMissingIds, forKey: .allowMissingIds)
    try container.encodeIfPresent(self.deviceInfo, forKey: .deviceInfo)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.RequestMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
