// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response for SearchJob method.
public struct SearchJobsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Job entities that match the specified
  /// [SearchJobsRequest][google.cloud.talent.v4.SearchJobsRequest].
  ///
  /// [google.cloud.talent.v4.SearchJobsRequest]: <doc:SearchJobsRequest>
  public var matchingJobs: [SearchJobsResponse.MatchingJob] = []

  /// The histogram results that match with specified
  /// [SearchJobsRequest.histogram_queries][google.cloud.talent.v4.SearchJobsRequest.histogram_queries].
  ///
  /// [google.cloud.talent.v4.SearchJobsRequest.histogram_queries]: <doc:SearchJobsRequest/histogramQueries>
  public var histogramQueryResults: [HistogramQueryResult] = []

  /// The token that specifies the starting position of the next page of results.
  /// This field is empty if there are no more results.
  public var nextPageToken: Swift.String = Swift.String()

  /// The location filters that the service applied to the specified query. If
  /// any filters are lat-lng based, the
  /// [Location.location_type][google.cloud.talent.v4.Location.location_type] is
  /// [Location.LocationType.LOCATION_TYPE_UNSPECIFIED][google.cloud.talent.v4.Location.LocationType.LOCATION_TYPE_UNSPECIFIED].
  ///
  /// [google.cloud.talent.v4.Location.LocationType.LOCATION_TYPE_UNSPECIFIED]: <doc:Location/LocationType/unspecified>
  /// [google.cloud.talent.v4.Location.location_type]: <doc:Location/locationType>
  public var locationFilters: [Location] = []

  /// Number of jobs that match the specified query.
  ///
  /// Note: This size is precise only if the total is less than 100,000.
  public var totalSize: Swift.Int32 = Swift.Int32()

  /// Additional information for the API invocation, such as the request
  /// tracking id.
  public var metadata: ResponseMetadata? = nil

  /// If query broadening is enabled, we may append additional results from the
  /// broadened query. This number indicates how many of the jobs returned in the
  /// jobs field are from the broadened query. These results are always at the
  /// end of the jobs list. In particular, a value of 0, or if the field isn't
  /// set, all the jobs in the jobs list are from the original
  /// (without broadening) query. If this field is non-zero, subsequent requests
  /// with offset after this result set should contain all broadened results.
  public var broadenedQueryJobsCount: Swift.Int32 = Swift.Int32()

  /// The spell checking result, and correction.
  public var spellCorrection: SpellingCorrection? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SearchJobsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchJobsResponse().with { $0.matchingJobs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let matchingJobs = CodingKeys(stringValue: "matchingJobs")
    static let histogramQueryResults = CodingKeys(stringValue: "histogramQueryResults")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let locationFilters = CodingKeys(stringValue: "locationFilters")
    static let totalSize = CodingKeys(stringValue: "totalSize")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let broadenedQueryJobsCount = CodingKeys(stringValue: "broadenedQueryJobsCount")
    static let spellCorrection = CodingKeys(stringValue: "spellCorrection")

    static let _knownKeys: Set<Swift.String> = [
      "matchingJobs",
      "histogramQueryResults",
      "nextPageToken",
      "locationFilters",
      "totalSize",
      "metadata",
      "broadenedQueryJobsCount",
      "spellCorrection",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [SearchJobsResponse.MatchingJob].self, forKey: .matchingJobs)
    {
      self.matchingJobs = value
    }
    if let value = try container.decodeIfPresent(
      [HistogramQueryResult].self, forKey: .histogramQueryResults)
    {
      self.histogramQueryResults = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([Location].self, forKey: .locationFilters) {
      self.locationFilters = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalSize) {
      self.totalSize = value
    }
    self.metadata = try container.decodeIfPresent(ResponseMetadata.self, forKey: .metadata)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .broadenedQueryJobsCount)
    {
      self.broadenedQueryJobsCount = value
    }
    self.spellCorrection = try container.decodeIfPresent(
      SpellingCorrection.self, forKey: .spellCorrection)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.matchingJobs, forKey: .matchingJobs)
    try container.encode(self.histogramQueryResults, forKey: .histogramQueryResults)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.locationFilters, forKey: .locationFilters)
    try container.encode(self.totalSize, forKey: .totalSize)
    try container.encodeIfPresent(self.metadata, forKey: .metadata)
    try container.encode(self.broadenedQueryJobsCount, forKey: .broadenedQueryJobsCount)
    try container.encodeIfPresent(self.spellCorrection, forKey: .spellCorrection)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Job entry with metadata inside
  /// [SearchJobsResponse][google.cloud.talent.v4.SearchJobsResponse].
  ///
  /// [google.cloud.talent.v4.SearchJobsResponse]: <doc:SearchJobsResponse>
  public struct MatchingJob: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Job resource that matches the specified
    /// [SearchJobsRequest][google.cloud.talent.v4.SearchJobsRequest].
    ///
    /// [google.cloud.talent.v4.SearchJobsRequest]: <doc:SearchJobsRequest>
    public var job: Job? = nil

    /// A summary of the job with core information that's displayed on the search
    /// results listing page.
    public var jobSummary: Swift.String = Swift.String()

    /// Contains snippets of text from the
    /// [Job.title][google.cloud.talent.v4.Job.title] field most closely matching
    /// a search query's keywords, if available. The matching query keywords are
    /// enclosed in HTML bold tags.
    ///
    /// [google.cloud.talent.v4.Job.title]: <doc:Job/title>
    public var jobTitleSnippet: Swift.String = Swift.String()

    /// Contains snippets of text from the
    /// [Job.description][google.cloud.talent.v4.Job.description] and similar
    /// fields that most closely match a search query's keywords, if available.
    /// All HTML tags in the original fields are stripped when returned in this
    /// field, and matching query keywords are enclosed in HTML bold tags.
    ///
    /// [google.cloud.talent.v4.Job.description]: <doc:Job/description>
    public var searchTextSnippet: Swift.String = Swift.String()

    /// Commute information which is generated based on specified
    ///  [CommuteFilter][google.cloud.talent.v4.CommuteFilter].
    ///
    /// [google.cloud.talent.v4.CommuteFilter]: <doc:CommuteFilter>
    public var commuteInfo: SearchJobsResponse.CommuteInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MatchingJob`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MatchingJob().with { $0.job = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let job = CodingKeys(stringValue: "job")
      static let jobSummary = CodingKeys(stringValue: "jobSummary")
      static let jobTitleSnippet = CodingKeys(stringValue: "jobTitleSnippet")
      static let searchTextSnippet = CodingKeys(stringValue: "searchTextSnippet")
      static let commuteInfo = CodingKeys(stringValue: "commuteInfo")

      static let _knownKeys: Set<Swift.String> = [
        "job",
        "jobSummary",
        "jobTitleSnippet",
        "searchTextSnippet",
        "commuteInfo",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.job = try container.decodeIfPresent(Job.self, forKey: .job)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobSummary) {
        self.jobSummary = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobTitleSnippet) {
        self.jobTitleSnippet = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .searchTextSnippet) {
        self.searchTextSnippet = value
      }
      self.commuteInfo = try container.decodeIfPresent(
        SearchJobsResponse.CommuteInfo.self, forKey: .commuteInfo)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.job, forKey: .job)
      try container.encode(self.jobSummary, forKey: .jobSummary)
      try container.encode(self.jobTitleSnippet, forKey: .jobTitleSnippet)
      try container.encode(self.searchTextSnippet, forKey: .searchTextSnippet)
      try container.encodeIfPresent(self.commuteInfo, forKey: .commuteInfo)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.talent.v4.SearchJobsResponse.MatchingJob"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Commute details related to this job.
  public struct CommuteInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Location used as the destination in the commute calculation.
    public var jobLocation: Location? = nil

    /// The number of seconds required to travel to the job location from the
    /// query location. A duration of 0 seconds indicates that the job isn't
    /// reachable within the requested duration, but was returned as part of an
    /// expanded query.
    public var travelDuration: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CommuteInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CommuteInfo().with { $0.jobLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let jobLocation = CodingKeys(stringValue: "jobLocation")
      static let travelDuration = CodingKeys(stringValue: "travelDuration")

      static let _knownKeys: Set<Swift.String> = [
        "jobLocation",
        "travelDuration",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.jobLocation = try container.decodeIfPresent(Location.self, forKey: .jobLocation)
      self.travelDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .travelDuration)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.jobLocation, forKey: .jobLocation)
      try container.encodeIfPresent(self.travelDuration, forKey: .travelDuration)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.talent.v4.SearchJobsResponse.CommuteInfo"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.SearchJobsResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
