// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleWKT
import GoogleGax

extension Clients {
  protocol TenantServiceStub: Sendable {
    func createTenant(
      request: CreateTenantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    func getTenant(
      request: GetTenantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    func updateTenant(
      request: UpdateTenantRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    func deleteTenant(
      request: DeleteTenantRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listTenants(
      request: ListTenantsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListTenantsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
