// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TenantServiceLogging: TenantServiceStub {
    let inner: any TenantServiceStub
    let logger: Logger

    public init(_ inner: any TenantServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-talent-v4"
      logger[metadataKey: "gcp.client.service"] = "jobs"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TenantService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createTenant(
      request: CreateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTenant",
        action: {
          (r: CreateTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.createTenant(request: r, options: o)
        })
    }

    public func getTenant(
      request: GetTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTenant",
        action: {
          (r: GetTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.getTenant(request: r, options: o)
        })
    }

    public func updateTenant(
      request: UpdateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTenant",
        action: {
          (r: UpdateTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.updateTenant(request: r, options: o)
        })
    }

    public func deleteTenant(
      request: DeleteTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTenant",
        action: { (r: DeleteTenantRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTenant(request: r, options: o)
        })
    }

    public func listTenants(
      request: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListTenantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTenants",
        action: {
          (r: ListTenantsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.ListTenantsResponse
          in
          return try await self.inner.listTenants(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
