// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax

extension Clients {
  final class TenantServiceRetry: TenantServiceStub {
    let inner: any TenantServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any TenantServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createTenant(
      request: CreateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.createTenant(request: r, options: o)
        })
    }

    public func getTenant(
      request: GetTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.getTenant(request: r, options: o)
        })
    }

    public func updateTenant(
      request: UpdateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTenantRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.Tenant
          in
          return try await self.inner.updateTenant(request: r, options: o)
        })
    }

    public func deleteTenant(
      request: DeleteTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteTenantRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTenant(request: r, options: o)
        })
    }

    public func listTenants(
      request: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListTenantsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTenantsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTalentV4.ListTenantsResponse
          in
          return try await self.inner.listTenants(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
