// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleCloudGax

/// A service that handles tenant management, including CRUD and enumeration.
///
/// @Snippet(path: "TenantServiceQuickstart")
public class TenantServiceClient: Clients.TenantServiceProtocol {
  let inner: any Clients.TenantServiceStub

  /// Creates a new `TenantServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TenantServiceStub = try Clients.TenantServiceTransport(options)
    inner = Clients.TenantServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TenantServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new tenant entity.
  ///
  /// @Snippet(path: "TenantService_CreateTenant")
  public func createTenant(
    request: CreateTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    try await self.inner.createTenant(request: request, options: options)
  }

  /// Retrieves specified tenant.
  ///
  /// @Snippet(path: "TenantService_GetTenant")
  public func getTenant(
    request: GetTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    try await self.inner.getTenant(request: request, options: options)
  }

  /// Updates specified tenant.
  ///
  /// @Snippet(path: "TenantService_UpdateTenant")
  public func updateTenant(
    request: UpdateTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    try await self.inner.updateTenant(request: request, options: options)
  }

  /// Deletes specified tenant.
  ///
  /// @Snippet(path: "TenantService_DeleteTenant")
  public func deleteTenant(
    request: DeleteTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteTenant(request: request, options: options)
  }

  /// Lists all tenants associated with the project.
  ///
  /// @Snippet(path: "TenantService_ListTenants")
  public func listTenants(
    request: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.ListTenantsResponse {
    try await self.inner.listTenants(request: request, options: options)
  }

  /// Lists all tenants associated with the project.
  ///
  /// @Snippet(path: "TenantService_ListTenants")
  public func listTenants(
    byItem: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Tenant, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudTalentV4.ListTenantsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTenants(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "TenantService_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TenantServiceClient`.
  ///
  /// To mock `TenantServiceClient` change your functions to receive
  /// `some TenantServiceProtocol` or `any TenantServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TenantServiceProtocol {
    /// See `TenantServiceClient.createTenant`.
    func createTenant(request: CreateTenantRequest) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.createTenant`.
    func createTenant(
      parent: Swift.String,
      tenant: Tenant?,
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.getTenant`.
    func getTenant(request: GetTenantRequest) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.getTenant`.
    func getTenant(
      name: Swift.String,
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.updateTenant`.
    func updateTenant(request: UpdateTenantRequest) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.updateTenant`.
    func updateTenant(
      tenant: Tenant?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.deleteTenant`.
    func deleteTenant(request: DeleteTenantRequest) async throws

    /// See `TenantServiceClient.deleteTenant`.
    func deleteTenant(
      name: Swift.String,
    ) async throws

    /// See `TenantServiceClient.listTenants`.
    func listTenants(request: ListTenantsRequest) async throws
      -> GoogleCloudTalentV4.ListTenantsResponse

    /// See `TenantServiceClient.listTenants`.
    func listTenants(
      byItem: ListTenantsRequest
    ) throws -> any AsyncSequence<Tenant, Swift.Error>

    /// See `TenantServiceClient.listTenants`.
    func listTenants(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Tenant, Swift.Error>

    /// See `TenantServiceClient.createTenant`.
    func createTenant(
      request: CreateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.getTenant`.
    func getTenant(
      request: GetTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.updateTenant`.
    func updateTenant(
      request: UpdateTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.Tenant

    /// See `TenantServiceClient.deleteTenant`.
    func deleteTenant(
      request: DeleteTenantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `TenantServiceClient.listTenants`.
    func listTenants(
      request: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTalentV4.ListTenantsResponse

    /// See `TenantServiceClient.listTenants`.
    func listTenants(
      byItem: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Tenant, Swift.Error>
  }
}

// Default implementations
extension Clients.TenantServiceProtocol {
  public func createTenant(request: CreateTenantRequest) async throws -> GoogleCloudTalentV4.Tenant
  {
    try await self.createTenant(request: request, options: .init())
  }

  public func createTenant(
    request: CreateTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTenant(
    parent: Swift.String,
    tenant: Tenant?,
  ) async throws -> GoogleCloudTalentV4.Tenant {
    let request = CreateTenantRequest().with {
      $0.parent = parent
      $0.tenant = tenant
    }
    return try await self.createTenant(request: request)
  }

  public func getTenant(request: GetTenantRequest) async throws -> GoogleCloudTalentV4.Tenant {
    try await self.getTenant(request: request, options: .init())
  }

  public func getTenant(
    request: GetTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTenant(
    name: Swift.String,
  ) async throws -> GoogleCloudTalentV4.Tenant {
    let request = GetTenantRequest().with {
      $0.name = name
    }
    return try await self.getTenant(request: request)
  }

  public func updateTenant(request: UpdateTenantRequest) async throws -> GoogleCloudTalentV4.Tenant
  {
    try await self.updateTenant(request: request, options: .init())
  }

  public func updateTenant(
    request: UpdateTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.Tenant {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTenant(
    tenant: Tenant?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudTalentV4.Tenant {
    let request = UpdateTenantRequest().with {
      $0.tenant = tenant
      $0.updateMask = updateMask
    }
    return try await self.updateTenant(request: request)
  }

  public func deleteTenant(request: DeleteTenantRequest) async throws {
    try await self.deleteTenant(request: request, options: .init())
  }

  public func deleteTenant(
    request: DeleteTenantRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTenant(
    name: Swift.String,
  ) async throws {
    let request = DeleteTenantRequest().with {
      $0.name = name
    }
    try await self.deleteTenant(request: request)
  }

  public func listTenants(request: ListTenantsRequest) async throws
    -> GoogleCloudTalentV4.ListTenantsResponse
  {
    try await self.listTenants(request: request, options: .init())
  }

  public func listTenants(
    request: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTalentV4.ListTenantsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTenants(
    byItem: ListTenantsRequest
  ) throws -> any AsyncSequence<Tenant, Swift.Error> {
    try self.listTenants(byItem: byItem, options: .init())
  }

  public func listTenants(
    byItem: ListTenantsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Tenant, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudTalentV4.ListTenantsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTenants(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Tenant, Swift.Error> {
    let request = ListTenantsRequest().with {
      $0.parent = parent
    }
    return try self.listTenants(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
