// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request for updating a specified company.
public struct UpdateCompanyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The company resource to replace the current resource in the
  /// system.
  public var company: Company? = nil

  /// Strongly recommended for the best service experience.
  ///
  /// If [update_mask][google.cloud.talent.v4.UpdateCompanyRequest.update_mask]
  /// is provided, only the specified fields in
  /// [company][google.cloud.talent.v4.UpdateCompanyRequest.company] are updated.
  /// Otherwise all the fields are updated.
  ///
  /// A field mask to specify the company fields to be updated. Only
  /// top level fields of [Company][google.cloud.talent.v4.Company] are
  /// supported.
  ///
  /// [google.cloud.talent.v4.Company]: <doc:Company>
  /// [google.cloud.talent.v4.UpdateCompanyRequest.company]: <doc:UpdateCompanyRequest/company>
  /// [google.cloud.talent.v4.UpdateCompanyRequest.update_mask]: <doc:UpdateCompanyRequest/updateMask>
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Initialize a new instance of `UpdateCompanyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateCompanyRequest().with { $0.company = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.UpdateCompanyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
