// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for updating a specified tenant.
public struct UpdateTenantRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The tenant resource to replace the current resource in the
  /// system.
  public var tenant: Tenant? = nil

  /// Strongly recommended for the best service experience.
  ///
  /// If [update_mask][google.cloud.talent.v4.UpdateTenantRequest.update_mask] is
  /// provided, only the specified fields in
  /// [tenant][google.cloud.talent.v4.UpdateTenantRequest.tenant] are updated.
  /// Otherwise all the fields are updated.
  ///
  /// A field mask to specify the tenant fields to be updated. Only
  /// top level fields of [Tenant][google.cloud.talent.v4.Tenant] are supported.
  ///
  /// [google.cloud.talent.v4.Tenant]: <doc:Tenant>
  /// [google.cloud.talent.v4.UpdateTenantRequest.tenant]: <doc:UpdateTenantRequest/tenant>
  /// [google.cloud.talent.v4.UpdateTenantRequest.update_mask]: <doc:UpdateTenantRequest/updateMask>
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `UpdateTenantRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateTenantRequest().with { $0.tenant = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.talent.v4.UpdateTenantRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
